### ISSUE TITLE
Gym Note Support

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#107]
Prelude to a feature request:
We have some gyms that players should not be raiding at. We also have a few gyms where players can raid, but there are caveats to raiding there that cannot be ignored (parking restrictions, smoking policies, etc).
Possible solution: Allow notes to be tagged to gyms that can show as big red text in the raid channel when a user joins.
There are probably better solutions, hence prelude to a feature request.

**Requestor**: TheRealStickman

**Comment by fortepc** [comment]
Honestly, while these sorts of notes have the potential to help warn
somebody who may not know about the situation that is in your community, it
can also backfire as there are some vindictive people who like to stir
trouble when they get these kind of warnings. The best thing to do for this
type of situation is usually to just make a relationship with the property
owners who have issue with the gym, assure them that you will do what you
can inside of your community to handle it, and make sure they're aware that
the community supports taking action against individual offenders, and will
support them if they end up deciding to remove the gym out right, by making
sure that they know how to get it removed.

**Comment by fortepc** [comment]
Just to add in later, I do still like and support this feature addition.

**Comment by cupkait** [comment]
I would also really like to see this feature. I believe it is/should be up to the server admins/mods to determine what information should be shared to benefit the community best.

We have multiple gyms where a notice of "park in this spot rather than that spot to avoid disrupting the business traffic" or "avoid on Sunday mornings before 2pm" would be extremely beneficial as a consistent gym note.

**Comment by dandesousa** [comment]
This feature is starting to make more sense with the new community poi -- going to think this through w.r.t aliases as well.

**Comment by sunkast** [comment]
I also would use this feature.

**Comment by fortepc** [comment]
Yeah, I'm much more in support of this feature now than my first message would suggest.
