### ISSUE TITLE
Sub-raid groups within a raid channel

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#109]
Discussion / Possibility:

```
dml238
Request: For ex-raid channels, add role for raid creator/mod to set group times trainers can "sign up" for, ex. "Hatch" , "Hatch+15min ", "Hatch+30mins".  Given the size of some of the ex-raid channels this could help provide some clarity
```

**Comment by fortepc** [comment]
So, would the group times be predetermined like exampled above, or would it be up to raid mods to determine? 

raidcreator: $set starttime 3:40pm`
PokeNav: Raid Start Time set for 3:40pm
raidmod: $set starttime 3:55pm
PokeNav: Existing start time already set for 3:40pm, would you like to overwrite? or create new?
:ok:  Overwrite
:new: Create New

**Comment by fortepc** [comment]
To make this sub-groups feature work better with #192, it could also be a named group, so like an raid mod or raid organizer can run `$set starttime group1 4:30pm`, PokeNav wouldn't have to actually know what "group1" actually is, just recognize the string as unique timer and post a message in the channel `PokeNav: group1 your starttime is now!`
