### ISSUE TITLE
Feature Suggestion: Meowth Compatibility for text command based Raid Reporting

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#110]
Lots of servers are already running meowth, and their biggest reason for not switching to another bot is the fear of "rocking the boat" so to speak. Their users already know and are used to working with Meowth and are worried that migrating over will upset their current reporting levels and cause problems.

**Comment by dandesousa** [comment]
Meowth 3 has changes a bunch of commands and they are actually closer to what we already have -- going to close this out for now as I'm being aggressive with cleanup of issues going forward. Feel free to re-open it with examples.
