### ISSUE TITLE
Channel name for raids should include the gym name even if it is not detected by PokeNav

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#124]

**Comment by bradders2000** [comment]
![a6e4a1c2-a8fe-4ac9-a773-a8d2b9920972](https://user-images.githubusercontent.com/42442214/44836785-c5fe0700-ac2f-11e8-913b-3a1314c34bc4.png)

This is a new gym, upgraded from an existing pokestop. The channel name itself contains the name ocr’d from the screenshot, but it’s missing from the notification, which just says ‘Regirock until xx:xx:xx’ with no mention of which gym it’s at. 

We have a few ingress players in the area and they’re going a bit crazy with portal submissions at the moment, so this type of thing is happening a lot.

**Comment by dandesousa** [comment]
Not sure whether this still makes sense given the alias and POI addition feature and notification feature -- the absence makes it clear it didn't link to a gym and while the channel name includes it, only the notification / title text does not.

A mistyped alias could give the false impression that work, whereas keeping the status quo will make it clear that the gym was linked.

**Comment by dandesousa** [comment]
If people feel really strongly about this we can enter it but I haven't seen it requested a ton.
