### ISSUE TITLE
QR Code Support For Trainer Profiles

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#133]
A way for users to store their QR codes for reference by other trainers

Use Case: scan via a desktop app

**Comment by fortepc** [comment]
Their QR Codes are literally nothing more than their friend codes, so instead of storing their QR Code, just generate one on the fly with their friend code.

**Comment by dandesousa** [comment]
thats how it would be done for the subset of trainers that set a valid friend code -- realistically this is a pretty low priority right now

**Comment by dandesousa** [comment]
Reconsidering this since its been a while and requested by multiple people

**Comment by dandesousa** [comment]
`$qr @mention` for a user to bring up the code is the new request (this can also potentially just be implemented as part of some of the embeds as well, assuming they don't increase the size too much).

**Comment by RitrokPoGo** [comment]
thanks for reopening this, i'm not a coder or have input on that ascpect, i have another bot i use simply for friend codes and it has it as part of the functions if you were interested in looking at it and maybe you can see its code from the bot, i dont know its 
https://nursejoy.xyz/
Thanks again

**Comment by lewymd** [comment]
Just adding support for this as it would still be useful, could be placed in the embed, maybe even replacing the picture of the Pokemon?

**Comment by dandesousa** [comment]
Added in remote raid welcome message -- will expand to other areas based on initial tests and user feedback
