### ISSUE TITLE
Trainer Profile Link: Photodex

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#147]
New account to be able to link to your profile: Photodex.io

`$link photodex Trainer_Forte` links my PokeNav profile to https://www.photodex.io/Trainer_Forte

**Comment by dandesousa** [comment]
Neat -- this is just to get a link to the profile right? This should be straightforward

**Comment by dandesousa** [comment]
You've reminded me it exists -- which I lost track of with all the other stuff going on. No update at this time.
