### ISSUE TITLE
Have help text from commands link in subtext to the documentation website

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#148]
Request: 
Add a link to [The documentation website](http://docs.pokenavbot.com) to the subtext of every help command responce, and command syntax error responce. 

Reason: 
[The documentation website](http://docs.pokenavbot.com) is a super valuable resource for users who are confused and for those who may not be familiar with commands in general, can be easier to understand than the `$help` commands for some users.

**Comment by dandesousa** [comment]
going to be tackled in #460
