### ISSUE TITLE
Support Nest Reporting In PokeNav

### ISSUE THREAD

**Issue by DazzaJay** [PokeNavBot/issue-tracker#162]
Feature Requests: Active Nests.

The users in our local PoGo Discord have asked a few times for a Nest system. Where say, a user could report a nest near Gyms/Pokestops. Such as $Nest Abra Macpherson Park

And with that, a nest is listed in an "Active Nests" Channel. And stays there until either deleted, OR the "Nest Migration" timer ends. (As the end of nests are predictable)
Nest Migration Timer: http://nestmigration.com/

**Comment by dandesousa** [comment]
I'd love to integrate with the silph road's nest atlas.

I am going to mark this as blocked until they either provide an API and we know more about the upcoming nest / park changes to spawns.

Though eventually I'll get tired of waiting for the API :).

**Comment by adetia9** [comment]
I'd love to see nest reports go into a nice, tidy list.

**Comment by dandesousa** [comment]
Done waiting for TSR -- actively exploring nests in PokeNav.

This step ticket will encompass stage 1, which will be to attempt a global extraction of all nest data from OSM dumps for verification by local communities.

**Comment by TheGerontocracy** [comment]
This will be a killer feature and an amazing marketing tool for my server! We already have way better nest data than TSR without much technological help and I really look forward to seeing nests in the API so we get the data on pgmap.org. 

Not sure how it's planned implemented, but I hope we can report with screenshots of pokestops similar to quest. (Checking if a location is within a closed osm way should be realtively easy.)

**Comment by mikosoby** [comment]
In our community we only submit data for big nests(parks usually) and small nests for the like a single-spawnpoint-nest near the PokéStop are left to TSR Atlas.
And so I am not so sure about submitting nests through images of PokeStops unless one can group them somehow.

It might be a better idea to create an area(not sure if it's possible to somehow declare a polygon on google maps or open street maps or pgmap.org) that will be set as a nest and this could be assinged to PokeNav.

**Comment by dandesousa** [comment]
Suggesting using PokeCloud for now
