### ISSUE TITLE
POI Submissions: Community POI and Commands

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/Issue-Tracker#180]
**Motivation**

Communities need more control over their POI, to add new points that will be revealed in the app, to get gym directions and enforce deduplication.

**Current Situation**

Right now, users fill out a form which gets initial POI loaded into a database for their area. This is good as it also helps other communities in the same area, but results in a 1-7 day wait and multiple steps to completed. POI are shared by all communities and verified but this still results in duplicates and missing POI that need to be re-added on an external service.

**Problems To Solve**

- Communities able to submit POI directly through the bot or app which are available instantly
- Communities able to share and verify each others POI in the same area
- Communities able to specify "preferences" or hide POI for those not desired or correct (effectively removing POI)
- Communities able to "download" their POI data as part of the open data initiative through Patreon. Their POI, their data.
- Communities able to specific "aliases" for gyms that make manual commands or gym / stop lookups easier

**Comment by dandesousa** [comment]
**Proposal: Feedback Requested**

Proposing the following changes for the first version of how community supported POI works to solve the immediate problems:

**_Automatic POI Bootstraps_**

When a community sets up for the first time, they run a command on their server called `request-poi` which will request bootstrapping of their community. This will replace the form and get them majority coverage of their area. Use of this command is limited or one-time.

**_Adding / Deleting POI_**

Going forward, all new POI will be added and managed by community admins in the #pokenav channel.

The following creates a new poi which is specific to your community:

`$create poi gym "Exact Name Of Gym" lat lon`
`$create poi pokestop "Exact Name Of Pokestop" lat lon`

These commands fail if the lat Lon does not fall in your communities play area.

These stops are immediately available to your server, do not require verification.

The number of gyms or stops a single community can submit initially will be limited probably but high (in the think 100s to 1000s but not 10,000)

You can find / list your submitted POI using the follow commands

`$gi "Name of Gym"`
`$si "Name of Gym"`

which will be updated to do a search of your gyms, including partial matches.

You can delete POI using:

`$delete poi id-number`

Deleting a POI will "hide" it from view.

**_Gym and Stop Aliases_**

Admins can create a single alias for a gym / stop in their community. This alias will be listed in the gym info and be able to be used as an exact, case insensitive match for a gym / stop. 

`$create alias "War" id-number`

The alias can be used either on a verified POI or one you created. 

If you do 

`$gym War`
`$gi War`
`$r Mewtwo War 45`

It will recognize the gym and set it, even if there are duplicates in the database. This effectively lets you provide a default and hides all other gyms from being used as that alias. 

**Question:** Will this potentially cause problems if you set the gym to something like Starbucks and need to deduplicate? Maybe defaults should be done another way

**_Sharing With Server / Promoting POI To Verified_**

TBD

**_Open Data_**

The data you submit to PokeNav is yours, it will be available for download to the you and the public at a future TBD url as a set of files.

**Comment by fortepc** [comment]
Could this also support a csv upload?

**Comment by dandesousa** [comment]
To contain scope and release incrementally I'm breaking this ticket up

#197 
#198 
#199 
#200 

This will be for all the backend database changes and commands required to add POI and resolve the combined community and verified POI, with aliases, file uploads, verification and open data to follow as updates.
