### ISSUE TITLE
Research/quest support in Pokenav

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/Issue-Tracker#181]
**Is your feature request related to a problem? Please describe.**
Not quite. Currently we're missing features to report ingame research which. Which results in reporting ingame research with a standard text format, which after a while gets a bit messy. 

**Describe the solution you'd like**
Implement support for ingame research in Pokenav, with the following features included: 

- Research can be submitted to the bot via a command (for example: $research)
- Research is submitted in 3 stages, where after each stage the bot will wait for a reply from the user (Much like how the bot waits for "here" in a raid channel, or how the bot waits for an answer when configuring a raid with the newly added edit button). The 3 stages being: Pokéstop name, Research Task, Reward. 
- When a research task is submitted like stated above, the Pokenav bot will send an embed message complete with all the information. If the name of the Pokéstop is typed correctly, it should also state directions to the pokéstop, just as done with raids. 
- A command to list all the reported tasks for the day (for example $list research). This list will be cleared every day after midnight, local time, according to the timezone set in the bot's server settings. Reported research messages should be retained, much like the channel where you report raids. Maybe the embed message of a expired quest could be updated, like is done with raids. 
- (optional) it would be great if the bot would delete the initial $research command message and the replies made to the bot after that.

Feel free to change the above to your own likings. What I stated above is just a sketch of the functionality as our community would like it to be. But maybe other communities have different opinions/wishes regarding this. 

**Describe alternatives you've considered**
We currently report ingame research via just text messages, but it gets a bit unclear and messy, especially with quests changing after midnight. 

**Additional context**

**Comment by dandesousa** [comment]
#140 is already tracking this -- so I have linked your comment there for reference and will close this as a duplicate
