### ISSUE TITLE
Increasing the $counter output

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/Issue-Tracker#182]
**Is your feature request related to a problem? Please describe.**
With an increasing amount of pokémon that players can use and with the coming of gen 4 as well, I find that the $counter command which currently shows the top 6 counters, is a bit limited.  With more pokémon available it's becomes more often that people might not have one of the 6 listed counters.

**Describe the solution you'd like**
Would it be possible to increase the counters output to maybe the 10 best counters, or even 12?

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by dandesousa** [comment]
@Rhendak 

I can see a couple options for implementing this -- I believe pokebattler supports up to 20 or 24, which discord could also support.

I can either make this an argument to counter and leave the default insertion to 6, so

`$c mewtwo 10`

And/or I can make a server setting that changes the default counter embed for everything done on that server.

I'm sort of leaning parameter to counter command unless you have a reason you want a different length sent at start (I can also see wanting to cleanup space).

What would you like?

**Comment by fortepc** [comment]
Any reason against both? Have it be an optional argument where server
owners can change the default output if no argument is given?

**Comment by Rhendak** [comment]
I'd rather go with the server setting that changes the default counter embed. 

I chose this over the extra argument to $counter because that would only make things more difficult for users that already find using bot commands difficult. I want to keep it as simple as possible for them.
