### ISSUE TITLE
A more aggressive version of clean red lobbies

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#186]
**Is your feature request related to a problem? Please describe.**
Multiple Region Support, when a server's coverage area is large enough there needs to be multiple reporting channels, the current clean raid lobbies setting still leaves behind idle chatter, making it not as useful as the #active-raids channel is.

**Describe the solution you'd like**
I'd like for the clean raids lobbies to be more aggressive. Deleting all messages from the channel, including chat messages. That way a regional raid reporting room is just like the 
#active-raids channel, just limited to that region's raids. PokeNav wouldn't need to be smart enough to know what that region is, it would just need to accept any raids reported by users in that region.

**Describe alternatives you've considered**
Ability to create and link region based `#active-raids` channels. 

**Additional context**
This request is made with this server in mind, https://discord.gg/epqzXnu A server currently run by Meowth that covers the majority of the Charlotte, NC area.

**Comment by dotbanana** [comment]
You can help you out with another bot for this purpose to get the system working as you want for now. I use: 
https://discordbots.org/bot/420013638468894731

**Comment by fortepc** [comment]
the thing is I don't want just commands cleaned up, I want all chat cleaned up. I don't want any chat or communication to happen at all in the reporting Channel.

**Comment by fortepc** [comment]
the only thing I want the channel used for is to share a screenshot of the raid and for pokenav to display all the currently running raids for that region, everything else should be deleted unless it's been posted by someone with server administrator rights.
