### ISSUE TITLE
Ability for Server admins to get a list of quota contributors

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/Issue-Tracker#187]

**Comment by cupkait** [comment]
Id love to see who is contributing and also who is using the quotas outside of just leaderboards.

**Comment by dandesousa** [comment]
List of top quota contributors is straightforward -- the breakdown of those using quota is not, see #188 comment. If you guys want a detailed quota report there would probably need to be some constraints (i.e. it would be aggregated daily, weekly, monthly or whatever).

We should track it separately from this.
