### ISSUE TITLE
Please implement a poll for possible times a raid can be started

### ISSUE THREAD

**Issue by chelloni** [PokeNavBot/issue-tracker#191]
this would really be useful. Just add a poll where the trainers can choose for example 13:00 or 13:15 or 13:30 or 13:45 where they COULD start and see when all the others also could start.
People in my area got used to the former Telegram bot. Just to make things easy.
Cheers! Great work!

**Comment by fortepc** [comment]
This is actually really easy to do manually, or with another bot dedicated to just creating the poll. There are actually more than a couple of poll bots available that may be worth looking into.

**Comment by fortepc** [comment]
Well, honestly I don't think it's a good idea to have that automatically have a poll. Most of the time the person who is organizing The Raid should be able to just decide and if it becomes an issue then someone can start a poll.
