### ISSUE TITLE
Support For Train Raid Lobbies

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#192]
**Is your feature request related to a problem? Please describe.**
One group, going from raid to raid as a group has to move from channel to channel. Leaving some users getting lost of which raid they're going to next to keep up with the group.

**Describe the solution you'd like**
The ability to start a "Raid Train" channel, where the channel is capable of seamlessly switching gyms/raids to keep the same group together for each raid. 

- It would need to be smart enough to know when the destination has moved to the next gym and reset everyone's "here" status
- It would need... [comment on this issue report and if I agree with it, I'll add it here]

**Describe alternatives you've considered**
[comment on this issue report and if I agree with it, I'll add it here]

**Additional context**
This feature could be used for regular community events with carpooling, and a caravan or with RaidBus.com I'll be sending a link to the community leaders in the RaidBus server to try to get some discussion input from them too.

**Comment by fortepc** [comment]
Maybe have support for a queue? The Raid train organizer could use a command to specify what the next raid they're going to is before the switch actually happens, then use some simple command to trigger the transition. 
```$train nextstop "Gym Name"```

**Comment by fortepc** [comment]
It would also be a good idea to have the train's current status pinned to the channel. It would pin a couple of messages, 

- The current raid info, including the boss, the gym, directions, etc.
- The queue, along with your current position in the queue. Showing ✔️ for completed raids, ❌ for skipped raids, and 🔘  for future raids, and 🔜  for the current raid.

**Comment by fortepc** [comment]
If the train doesn't want to use the queue option, it could just be as easy as using the `$gym` command to just set the current gym in the channel and letting the channel expiration not be linked directly to the raid / egg expiration. Instead of warning the channel is about to expire when the raid expires, it instead asks for the next raid target until the raid train is closed by the organizer or an admin. `$train end`

**Comment by fortepc** [comment]
It may also be a good idea to bring #109 into this too, so that train organizers can have pre-organized sub-groups for the raids for pre-assigned private groups. Not sure how useful this would be though. Would need more input from others.

**Comment by xxsytriskxx** [comment]
Onboard with the raid train functionality.

Although I can't say much about how to improve it, I'm curious to what's the community's workaround is currently?

If I understood correctly, there would only be one group of people forming the Raid Train, so you aren't currently facing two or more groups each forming their own Raid Train at the same time. This is also how our community raids together on Friday mornings (weekend over here), we do back to back raids with a bunch of drivers following each other for a few hours. 

At the moment we've set just one single #raiding-chat channel for coordination, meaning:
- Raid Leaders link the raid lobby channels and pin them in a format similar to "Raid #5 - #pokenav-raid-lobby-x"
- Raiders update on their ETA, if they've arrived, if their done for the day, etc. all on the #raiding-chat channel.
- Nobody is obligated to join the raid lobby channel but just open it for directions if they need it

It's worked well for us when we tried it out yesterday, might work for other communities as well.

**Comment by fortepc** [comment]
I really like @zfatkat 's take on utilizing the existing raid lobbies and reported raids for the train. I'd like times to be optional though. So instead of `$train add [time]` it could be `$train add` and it would add it to the end of the current train schedule. And allow manual adding of stops without having to use an existing raid by using the gym name in the train-chat. `$train add "gym name" [time]` in the `#train-chat` would add a stop either to the end of the current schedule, or if a time is specified, in whatever sequential order based on the scheduled time. 

And to expand on that a bit, it could also be useful to have trains named, for a few different reasons, namely being able to identify it so you can support multiple trains running at once. So in the `#active-raids` channel the train would show up as one of the raids available named instead of as a gym, as a train name, and tagging the `#train-name-chat` or `#train-name-schedule` in chat would do the same thing that tagging any other raid channel does. Add the 👤 button for people to join the train. Then running `$train add` with only one running train in the server would add it to that train, but if you had multiple active trains you would be able to do `$train add #train-schedule [time]`  to add that raid to that specific train.

**Comment by Kdog0073** [comment]
Looks like I'm late to the conversation. Raid train support was always wanted, but now it seems especially wanted with the possibility of this lunch hour becoming a usual thing.

The problem is managing people who are on the train versus people who only want to do 1-2 gyms and not hop on an entire train. I think the regular raid channels can still be used to coordinate. The raid train channel can just be a manager. "@raid-train-abcde The next raid is at x" and then react options for "join, skip, leave raid train". (The mentioned queue options could be nice functionality, as well as the ability to "hand over" the engineer role).

**Comment by dandesousa** [comment]
This is being worked on as part of the beta, for all intents and purposes this is **closed** and additional features will be discussed in their own tickets using the beta-raid-trains label.
