### ISSUE TITLE
Role / Whitelist For Bypassing Server Share Quota

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#204]
**Is your feature request related to a problem? Please describe.**
Users would like to bypass the server shared quota, allowing a different level of trust to moderators or scouts that don't limit quota usage.

**Comment by daadyrbarn** [comment]
A whitelist or a separate role might be best, so ppl who aren't raid mods can still be scouts.

**Comment by dandesousa** [comment]
Closing this until someone actually needs it instead of just an idea that might be useful
