### ISSUE TITLE
Raid Starting Command

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/issue-tracker#217]
**Is your feature request related to a problem? Please describe.**
When weather is inclement many trainers at a raid will stay in their vehicle it is difficult to communicate that everyone at the raid is starting the lobby if they are not paying attention to the lobby or Discord.

**Describe the solution you'd like**
A $starting command that mentions users in the raid channel who are marked as being at the raid so they are notified that they should join the raid lobby.

**Describe alternatives you've considered**
I have a custom command that simply states the raid is starting, but it is unable to mention the members who are in the raid channel to notify them that they should go into the raid lobby.

**Comment by fortepc** [comment]
You could just mention the channel role for the channel.

**Comment by fortepc** [comment]
There is always a channel role that is the exact same as the channel name, but a mentionable role

**Comment by sunkast** [comment]
It would be much easier to teach members to use 1 command they can use in any raid channel than trying to teach them how to mention the channel.

**Comment by dandesousa** [comment]
@Rehtreau PokeNav does have this through the `$status` command that updates the status line of the raid with whatever you want, including start time, status of the raid, instructions on raids to follow, etc.

**Comment by dandesousa** [comment]
I think I like the idea of a short command that does a quick announce to the room. Mentioned just the users that are marked as here might be troublesome for large groups potentially. How important is the distinction between tagging the users that are here and the users that are just in the raid role @sunkast ? I could see both since the members are listable but could get some pretty long messages...

**Comment by Qualibert** [comment]
By the way, we are working right now on this exact feature. We figured something like this (a little more complex): if a user send the keyword ''start'' , the bot add the ⚠ reaction, if user click on that, it would tag the missing members. Only if everyone is there or after a little time, it will let people use the reaction to change the status to : " Go! (username) @everyone "

![idee](https://user-images.githubusercontent.com/44094559/52542709-9faccd80-2d70-11e9-85f8-2421c3b10bb8.png)

**Comment by sunkast** [comment]
Ideally the announcement would tag anyone who is marked as here. Though perhaps it would be simpler to just create a second role that is assigned to a user when they say they are here, and that role then gets tagged. The way my server is set up is that the raid channels are public, so mentioning @everyone/@here/@raid-channel-name would tag EVERYONE that is in that channel regardless of whether they are actually participating in the raid, which would not be ideal.

**Comment by Qualibert** [comment]
Not ideal indeed. 

Isn't there already a role for each raid channel?

**Comment by dandesousa** [comment]
Yes the reason for the raid role is only for people who join the raid and avoid tagging everyone. The status of here is just in the database , theres no role for it. ideally there shouldn’t be anyone joined to the channel who isn’t participating and interested in whatever announcement.

**Comment by sunkast** [comment]
Ok yeah so @raid-channel-name would work fine. I just checked on my server and that would work just fine mentioning the raid channel role. This way anyone who has shown interest in the raid is tagged since there are some members who don't mark themselves as here.

This is what I currently have. It's just a custom command set up with Nadeko.

![20190211_162555000_ios](https://user-images.githubusercontent.com/4213265/52577697-a549f800-2df0-11e9-87e3-7ea36cde5fe8.png)

**Comment by dandesousa** [comment]
created: https://github.com/PokeNavBot/issue-tracker/issues/303

as a substitute for this since I feel like the spirit of it has changed a bit. Also since the need isn't super pressing I will wait to implement it to give people a chance to comment on shortcuts or the name of the commands.

I will target implementing it in the next release
