### ISSUE TITLE
Link to on-going raid post on duplicates

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#229]
(This issue is present while having raid-channel creation delayed)

When a user posts a raid in a lobby while there's already one active for that gym, he only gets:
**''The gym you specified already has an on-going raid'**

It would help if a link to the original active raid was included in the bot response to a duplicate. 
The user could then easily join / create a raid channel without looking for it.

**Comment by dandesousa** [comment]
No further follow up so closing it until further notice to reduce noise.
