### ISSUE TITLE
Setting Multiple Active Raid channels?

### ISSUE THREAD

**Issue by warror925** [PokeNavBot/issue-tracker#236]
Is there a command (method) to set multiple channels for cities so that our community can post the raid to the announcement channel and it will direct the active raids for THAT city to the That city’s channel? Currently I see where I can only set one active raid channel and one announcement channel.  Users have requested this because of confusion searching the entire active single raid channel for their city’s raids or scrolling through the entire list of auto created raid boss channels. The bot is awesome - I’ve played with it on a test server and investigating if this is even possible?

**Comment by sunkast** [comment]
You can have as many raid reporting lobbies as you wish by using the $enable-raid-lobby #channel command.

However I do support your idea of having a single lobby where raids are directed to a city category. I have members tell me that it's a lot easier having only one channel to remember where to post a raid to versus having several lobbies based on city where they have to remember which city to post their screenshot to.

**Comment by warror925** [comment]
I see. So by enabling the city channels and posting to the one announce channel- the bot will create the raid in the city channel based on its location and I assume it will create the raid boss channel in that city channel or maybe just list the boss channels as their own stand alone channels .. thank you

**Comment by dandesousa** [comment]
I believe this question was answered. Thanks sunkast.
