### ISSUE TITLE
Raid Notification toggle

### ISSUE THREAD

**Issue by cyngrrl** [PokeNavBot/issue-tracker#237]
**Is your feature request related to a problem? Please describe.**
Sort of, an annoyance really: If I join a raid lobby I have to also set notifications (too many steps on phone) or keep checking to see if there are updates

**Describe the solution you'd like**
A toggle to automatically turn on notifications for any Raid Lobby (channel) I join ($toggle joined-raid-notification)

**Describe alternatives you've considered**
A react emoji that would let me decide to receive notifications for that channel when I join a raid

**Additional context**
trying to get folks off of facebook where the raiding "system" is easy in that there is one massive chat and everyone gets pop-up notifications on their phone when in PoGo. One massive chat is problematic where multiple raid chatter gets confusing.

**Comment by fortepc** [comment]
This is a setting that each user has to set for themselves, the only way for the bot to do it would be if it were to tag people or the raid Channel roll

**Comment by fortepc** [comment]
That is unless I've totally misunderstood. if

**Comment by dandesousa** [comment]
Right this isn't something the bot can do. 

Notifications are a client / account setting on discord, therefore client would need to set there default notification settings for the server and then override it for each channel. 

The bot could do two things: tag you each time "something" happens, which would require a fair bit of checking for even simple commands in a raid lobby, or tag the entire group (which can't be separated into an individual setting).

The nice thing about PokeNav is that you can make the channels private; so if a user wants to enable notifications everyone / disable select channels, they can and they won't get any notifications for raids they aren't apart of (and they can opt into the channels they want to get active raids notifications for).

If you have additional questions about it mention me here or we can continue in the discord. Thanks.
