### ISSUE TITLE
Add a customizable field in raid embed

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#238]
As can effort to make Pokenav as user-friendly as possible, including other languages, it has been suggested to make some changes to the raid-channel cheatsheet:

**1)** Make the top message (embed) in a raid channel a pinned one.

**2)** Shorten the cheatsheet to a 1024 characters text with markdown (use aliases to identify commands). (The cheatsheet function could be removed at this point to have less posts in the raid channel)

**3)** Add a customizable field of 1024 characters (with usable markdown) to the top embed message in raid channels. 

**4)** Make the short cheatsheet the default text in that field (bonus points if pokenav can remember server that disable the cheatsheet and leave the field empty).

**5)** Create a new command usable in #pokenav : ``$set-cheatsheet "text"`` / ``$scs "text"`` that will change the custom field for all raids (bonus points if pokenav can update active raids embed). 

**All this, without removing any functionality, would allows every server to:** 
**A:** Translate commands by themself and cherry-pick which informations get on there
**B:** Add other bot commands that can be useful while operating pokenav
**C:** Create another type of player-aid like a short tutorial or step-by-step instructions.

**Comment by fortepc** [comment]
I think that this is an excellent idea.

**Comment by mikosoby** [comment]
bump

**Comment by mikosoby** [comment]
bump
