### ISSUE TITLE
Make the raid bosses list data useful

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#239]
With Pokenav ability to generate a raid bosses list from reports, using this information to upgrade the bot in the following ways:

**1) Add a command ``$tiers`` that summons the current available bosses by tiers.** 

This may or may not included the following informations: Icons/Graphic for the pokemon, Type, Weather Boost, CP Range, Counters, Recommended team size. 

This list also may or may not be self-updating (as a way or getting a pinned post in a channel with a updated list at all time).

**2) Upgrade the ''the egg has hatched, please update'' message in a raid channel with reaction-based update**

Adding a list of possible bosses for the egg tier in that message with numbers-emoji (1 to 5 for example) reaction. Using those reactions, members of the channel could pick the corresponding reaction to update the boss (leaving the ``$boss`` command probably available if it's a new boss).

(same thing as the pokenav response in case of duplicate gyms for example).

**3) Upgrade the ''Tools'' reaction update to have the same reaction system as above**

For server with delayed raid channels creation, they would need to be able to set the boss with DM to pokenav. Simply adding reactions with probable boss list for the tier in the DM message when the user click on ''update the boss'' would allow that. 

**4) Upgrade the raid embed with probable bosses for the tier**

If convenient, a raid embed currently on a ''egg'' could list probable bosses that can hatch for this tier, again maybe with small icons.

**Comment by fortepc** [comment]
Very much in favor of two and three, one and four I am fairly meh about
