### ISSUE TITLE
Configurable profile fields

### ISSUE THREAD

**Issue by tehstone** [PokeNavBot/issue-tracker#267]
**Is your feature request related to a problem? Please describe.**
My server uses a different bot for some of the features that PokeNav provides and users get confused when they see 0 raids reported or joined on their Pokenav profile

**Describe the solution you'd like**
Give server admins options to toggle various profile fields on or off.

**Comment by SpinDORK** [comment]
The profile layout is not mobile friendly as there are too many entries, give admins the ability to turn some entries on and off in order for the user to see their full profile on their phone.

**Comment by dandesousa** [comment]
Rather than make profile fields configurable I will first try to great condense and hide unused fields in the profile -- then you guys can put in a new ticket for hiding fields if you still have the use case.
