### ISSUE TITLE
Grant badges to more than one user at a time

### ISSUE THREAD

**Issue by tehstone** [PokeNavBot/issue-tracker#268]
**Is your feature request related to a problem? Please describe.**
I just gave a badge to 246 users and had to copy and paste the command each time. You can imagine how much fun that was.

**Describe the solution you'd like**
allow the grant-badge command to accept multiple users at one time. Even if it's still limited to 5 or 10 that would be much simpler.

**Comment by dandesousa** [comment]
currently this is supported via roles, I am about to start looking into better ways to grant badges so this will either be completed or closed with an alternative solution when that is settled on

**Comment by dandesousa** [comment]
See #354  -- going to keep this as role based for a lot of reasons (discord message length limits, rate limiting on responses, and the ability for people to self-assign the roles and admins to check). 

That ticket will make certain operations easier though.
