### ISSUE TITLE
Tagging of POIs for filtering into separate active-raids/active-research channels

### ISSUE THREAD

**Issue by daadyrbarn** [PokeNavBot/issue-tracker#271]
**Is your feature request related to a problem? Please describe.**
I run a pokedraft server in the largest city of our region. People from other towns are starting to join and would like to be able to use the raid reporting feature without cluttering the main active-raids channel with raids that the majority won't want to see.

**Describe the solution you'd like**
Gyms can currently be tagged as EX elligible, but the feature is not used for filtering at the moment. I would like to see the ability to add custom tags to POIs and then set up multiple active-raids/active-research channels that filter based on those tags.
Ex: I make a secondary active-raids channel called #small-town-1. I then assign the tag "small-town-1" to all the gyms in that town, and whenever a raid is posted for one of those gyms, it would go into the #small-town-1 channel. It could still go in the default channel as well, but I imagine multiple posts would create unnecessary work for the bot.

This would also provide the benefit of possibly having just a single dedicated screenshot channel, removing the hassle of having to select between multiple region specific lobbies every time you post a raid/research task.

**Describe alternatives you've considered**
Alternatively I guess you could set up a secondary bot to watch the active-raids channel and copy any posts into the preferred channels based on a list of POIs. But I'm not sure you would be able to properly utilize the pokenav features that way.

**Additional context**
Other implementations for regional division have been discussed in #161 and #40, so see those tickets for additional input.

**Comment by daadyrbarn** [comment]
We also use PokeNav on our general purpose server, and here we have the city split into 8 areas with 1 raid lobby for each. This results in an active-raids channel where maybe 80% of the raids posted will not be useful to 80% of the users.

**Comment by dandesousa** [comment]
I would consider this apart of #161 discussion, so will close this out as duplicate -- link will be maintained there.
