### ISSUE TITLE
Reporting Weather at Raid 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/issue-tracker#274]
I think it would aid people to know if a) they have the right counters, b) enough trainers, and even c) if the raid is weather boosted to have this feature

I'd like there to be a $weather command which similar to the other raid report features would allow for the weather there to be reported and updated (should it change)

this also aids in pokedraft where raid weather conditions are crucial

**Comment by dandesousa** [comment]
Already exists, closing and linking https://github.com/PokeNavBot/issue-tracker/issues/137
