### ISSUE TITLE
OCR Bug: Dots issue

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#277]
As requested by IVPips, I'm opening an issue here for a widespread OCR issue on my server.

We have a lot of gyms with **"T.r"** in their names (it's the city's acronym) and the OCR often reads it wrong. It's very common, about 1/4 of the screenshots posted have some type of issues like: **adding a dot at the end, omitting the dot, reading "Tin" / "Tor"/ "T.ri" / "Lir" and more.**

I gathered 74 screenshots from 7 gyms and their results as part of an effort to get them corrected and stop flooding the _#ocr-bugs_ channel. You can see it's from a bunch of different users and devices.

Those are only a sample of all the errors that slipped and were left uncorrected by us, there are a lot more.

**I selected 2 methods of making the files available, a imgur gallery and google drive:**
https://qualibert.imgur.com
https://drive.google.com/drive/folders/1IdcmdoURbfgt2o2AECTMNXacCjz4hpTi?usp=sharing

Thanks!

**Comment by dandesousa** [comment]
This is being worked on ATM through experimental scanner...
