### ISSUE TITLE
Support for more granularity wrt trainer raid status

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#283]
The problem is that it is currently difficult to tell through $m the difference between if a player is interested and if a player is on the way to a raid. It is also difficult to tell if a trainer is here, or if they have already completed the raid.

I would like to see a solution to include more granular individual statuses to include "Interested", "On the way", "Here", "Done", and leaving the channel. The bot can place people who join the raid in an "interested" phase by default. The bot can recognize key phrases such as "coming", "going", "omw", "on my way" to update a person's status (and emoji in the $m listing). The "here" phase can remain the same, and a person who says "here" can do so from any status. After, phrases such as "complete" can update the member's status and emoji to show they have already completed the raid. Leaving the raid channel can remain the same.

Currently, many players will simply leave the channel upon completing a raid. This works, but there are a few use cases where it would have been nice for people to stick around in the chat such as needing additional people for a second group. As for distinguishing between interested and coming, it is next to impossible without encouraging people to text and drive to update their eta (which compromises safety).

This idea also stems from other discords and their usage of Professor Hemlock statuses.
![image](https://user-images.githubusercontent.com/6502797/51618033-146bb500-1ef3-11e9-9388-c70a584cadad.png)

**Comment by angiemjonas** [comment]
I agree with this proposal. Our community raids in 'groups' so it would allow the second group to know who has completed and who is still available to raid. I also like the idea of having both text commands as well as emojis.  Several struggle with scrolling to find the emoji so this gives the group options. Could there also be a command (separate from !cheatsheet) that would return just these options?
