### ISSUE TITLE
Track exraid statistics with Pokénav

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#285]
**Is your feature request related to a problem? Please describe.**
I've been keeping track of how many exraids each gym had (since a certain point) and when the latest date of an exraid on that specific gym was. However it's become a bit of a chore to keep track of it and I was wondering, couldn't Pokénav keep track of this automatically and output it in a nice list like I did?

**Describe the solution you'd like**
Pokénav to output exraid data in a message as can be seen in the screenshot below. It could work like the following: 
 
- The list can be pulled up with `$exraid` which outputs a list as can be seen in the screenshot below. 
- Ex-raid labeled gyms in Pokénav would be listed in in the list. 
- (optional/subject to change) Gyms could get labeled with a certain region, which orders them in the `$exraid` list under different region(labels).
- Pokénav would keep track automatically of each successfully linked gym that is labeled as exraid gym and gets a reported exraid on it. Hereby adding +1 to the total count of exraids on that gym and listing the date of latest exraid on this gym. 
- Server admins could reset the count on the exraid information with a command, hereby purging all exraid data for their own server. 

**Describe alternatives you've considered**
Keeping a list and updating it manually with each exraid wave, which is becoming a bit of a chore.

**Additional context**
![image](https://user-images.githubusercontent.com/1855295/51666637-a68cbf80-1fbe-11e9-873e-384155345b37.png)

**Comment by dandesousa** [comment]
bump -- interesting feature I want to review
