### ISSUE TITLE
Multiple Gyms/PoI Sort by Least Distance from Community's Set Center

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#286]
The underlying problem is that some stops/gyms like Starbucks will have many different PoIs to choose from. However, the more relevant ones are surrounded by irrelevant ones. So even if your gym/stop appears on the first page, it is likely to be buried as a middle or bottom option.

I would like the default sort to be based on the distance from the community's set center so the nearby and likely more relevant POI and gym options are most likely to be at the top.

This solution can be done using the haversine formula: (Python: https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points). 

There is another issue for pagination in #135 but even with pagination, it is still most ideal and user-friendly to have the most-likely relevant gyms/PoIs at the top of the first page

**Comment by TheGerontocracy** [comment]
For my area sorting by number of previous raids/quests reported would work better.
