### ISSUE TITLE
Translation for alola pokemon

### ISSUE THREAD

**Issue by ElKnarzo** [PokeNavBot/issue-tracker#287]
The bot does not recognize the combination "pokemon-form" if it is in another language, e.g. German is specified.

<img width="344" alt="grafik" src="https://user-images.githubusercontent.com/9089629/51785582-4e8ac000-215a-11e9-9637-b6e647e1b703.png">

**Comment by dandesousa** [comment]
This actually looks like a gap in the form name translations for those languages. I can probably fill these in for supported languages if the translation is missing.
