### ISSUE TITLE
PokeNav app Sharing server privacy settings 

### ISSUE THREAD

**Issue by nikikole** [PokeNavBot/issue-tracker#290]
I would like an option in the pokenav app to “hide” my server on the list that shows nearby servers on the profile page. I have a small test server I use kind of just for myself and a couple other people who are testing out bots and other options. I don’t really want this to appear on the list of nearby servers since it isn’t really being used to post raids and it’s not really for anyone to join. I don’t really want people to see it and ask for invites or for me to have to explain 100 times. Seems a lot simpler just to have a privacy option.

**Comment by dandesousa** [comment]
How would the person see it if they arent in it for the invite? It only shows servers you are in?

**Comment by dandesousa** [comment]
This is a pretty straightforward add to make it hidden. Im inclined to tie it to whether you are sharing with the app

**Comment by nikikole** [comment]
I see what you are saying. That makes sense.
