### ISSUE TITLE
Alolan Raid Boss OCR

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#291]
Scanning an alolan raid boss results in the normal form's picture and normal form's cheatsheet counters.

Reproduce with a raid picture of any alolan boss.
![image](https://user-images.githubusercontent.com/6502797/52077046-a5770780-2555-11e9-9a3f-70cb4b537d4d.png)

**Comment by dandesousa** [comment]
I had thought i had resolved this issue but may have introduced a regression. Will take a look for Saturdays release.
