### ISSUE TITLE
Option to not delete non-bot messages in active-raids channel.

### ISSUE THREAD

**Issue by Avaren** [PokeNavBot/issue-tracker#293]
**Is your feature request related to a problem? Please describe.**
The bot deletes all messages in the active-raids channel regardless of if the bot or user posted it. We find it useful to describe a channels use in the channel itself as we have a number of less discord savvy users. We would use the channel topic but they're pretty hidden on mobile.

**Describe the solution you'd like**
A toggle-able option to only delete the bots messages in active-raids instead of all messages.

**Describe alternatives you've considered**
Using another channel to describe use: People lose context, especially less savvy users. Can quickly forget what a channel is for or how to use it.
Use channel topic: Pretty hidden on mobile, not obvious.

**Comment by dandesousa** [comment]
@Avaren as a compromise on this and to bring it in line with other active raids channels as described in #315 -- pinned messages will no longer be deleted by the bot starting in the next update.

I believe this should resolve your issue as you can pin the message(s) you need to describe it. I will close the issue -- please mention me on this thread if this doesn't resolve the issue for you.
