### ISSUE TITLE
Support for "+" natural syntax for $with

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#296]
Most players indicate bringing additional players using syntax such as "+1", "+2" etc. To help players out, it would be nice if the bot interprets "+" as "$with ". For example, "+1i 1m" would be equivalent to "$w 1i 1m".

As another side note, if no team is specified (m, v, or i), add the player count to a neutral/unknown team". This would mean "+1" would function as the equivalent of "$w 1" which would add a player to an "unknown" team.

**Comment by dandesousa** [comment]
This feature will be mostly implemented as requested. Will implement the `+` alias for `$w` inside raids channels, as well as expand `+2m` as a valid syntax. I will expand unknown team support for `+` or `$w` but I will not expand it or allow it to be set for companion accounts (the default setting). 

As a shorthand when you don't know the right number of people, the unknown team can be useful. But I want to encourage people to set the right team, for display and pre-coordination purposes of splitting groups.
