### ISSUE TITLE
Trade Bot PM's not tagging

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/issue-tracker#300]
I know this is a Discord Embed issue, where it sometimes doesnt tag but instead just writes the ID number, so I was wonder if it would be possible to provide a plain text header of the persons discord name, much like the want ads themselves output into the header, just so that people dont need to keep asking me to look up the ID's for them...

**Comment by dandesousa** [comment]
So it should already be present in the header, as an example:

<img width="605" alt="Screen Shot 2019-04-19 at 8 37 37 PM" src="https://user-images.githubusercontent.com/3880281/56449060-04d9ed80-62e3-11e9-86c9-fa888ff95176.png">

at the top. If this is not what you meant please let me know (tag me in this ticket).
