### ISSUE TITLE
Ability to Organize Community Badges

### ISSUE THREAD

**Issue by gmagoto11** [PokeNavBot/issue-tracker#305]
I recently created a new community on discord and added PokeNav to it. When creating badges I noticed they were being listed newest first and oldest last. In the community I am at right now, the badges are listed from oldest to newest when you use the $available-badges function.

It would be nice if we were able to customize the order that badges appeared it so if you have tiered badges you can place them together. For example: we have tiered badges for number of gold gyms that were created between other badges so they are all out of ordered and hard to sort through. If that is not an option it would be nice to at least flip the order to oldest to newest.

We could toggle the badge and create news ones to replace to reorganize. But that would be a lot of work since you would have to revoke badges and then re-issue.

**Comment by Qualibert** [comment]
Really onboard with this too, I make custom 3D animated badges and it's taking some time. Right now I have to do a whole serie before creating them as badges to group them and hope that I'll never have to create ''higher'' or ''intermidiates'' tiers.

Ex: Report 50 raids, Report 100 Raids, Report 250 Raids.... etc

Having the ability to sort them by some kind of category or custom order would allow me to grant them as I create lower tiers for each categories and work my way up.

**Comment by dandesousa** [comment]
Do the the performance improvements I will be focusing on this week I've moved this back to "Considering" but will pick it back up in a week or so. For now I can partially implemented this (you can now sort by oldest, newest and name -- with name being the default to hopefully make this easier for people to find badges)

**Comment by dandesousa** [comment]
I will follow up on this to see if categories makes sense though this might lead to a larger improvement to badges overall.

**Comment by gmagoto11** [comment]
Excellent! Glad to see this will be moving forward. I am assuming instructions will be posted on how to sort once that is available?
