### ISSUE TITLE
Bug Reading Raid Screenshots with EX Tag

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#306]

**Comment by dandesousa** [comment]
Seeking localized tag screenshots...

**Comment by Qualibert** [comment]
French screenshot reads as "ARENE DE RAID EX"

https://cdn.discordapp.com/attachments/494512745312419851/548893704140881920/Screenshot_2019-02-23-10-47-03.jpg

![raid_ex_ocr](https://user-images.githubusercontent.com/44094559/53288707-a87ea580-3759-11e9-8c55-5024f1351363.png)
