### ISSUE TITLE
Allowing bots to use raid reactions to some degree

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#307]
**I'll put this request here just in case it's easily doable without side-effects:**

The current behavior is that pokenav let other bots report raids and anything related to commands, including joining a raid by writing ``+0`` or ``here`` in a raid channel. It won't allows them to use any reactions (join reaction, update reaction and delete reaction).

It could be useful to have, at least, bots able to create a raid channel by using the ''join'' reaction, they already can create raid channel by reporting in a lobby with ''immediately-create-channel'' toggled on (pokenav will create the channel but won't add the bot as a participant).

Updating and deleting raid could also be useful for others type of automation. 

The alternative right now is to have a hidden channel that create raid channels immediately only for the bot but creating a channel from a already reported raid demands that the bot ''hide'' the active-raid by deleting the whole post and recreated that itself in its private channel while toggling duplicate raid off and on.

**Comment by TheGerontocracy** [comment]
I also very much would like this feature. In my case for quests. 

Please make pokenav react to at least 🛠 and ❌ added by a bot, provided the bot is designated raid or research moderator.

**Comment by dandesousa** [comment]
Yeah the main concern is that bot users are sometimes different from regular users and the functions of a raid joining and membership are not thoroughly tested for bot users.

Is there a reason you want bots to be able to make rooms by default when users do not?

Maybe a better solution will be a way to override the channel setting and make a room immediately if the command is formatted a certain way, that way you can just have the bot make the room that way.

**Comment by Qualibert** [comment]
There quite a few projects that would be easier if bot were able to create rooms:
- Splitted active-raids channel, so joining from another location would create the room
- The channel map which could list active-raids and create room with corresponding numbered reactions
- Automated Raid channel tutorial which the bot could create a room for a new user

Some of those could be helped by being able to have a parameters to create a room even if it's disable, but not all. The modify and end reactions, I did not have immediate plans for them right now, but I can think of a few like allowing partial match on a gym name from a database if the OCR + aliases fail, auto-ending invalids raids from outside community....etc...etc.

Thank for considering!

**Comment by Qualibert** [comment]
We have a lot of errors on Ex-Raid gyms, most of them already have 10 aliases (the maximum) and continue to be misread in others way. Even with a custom bot that PM me each time it happens, I'm updating those way too often.

As you can see, I can get the right name even if it's misread with Levenstein distance, but currently I have to manually edit the gym.

It would save me so much time if I could let my bot correct OCR-bugs. :S
![OCR_misread](https://user-images.githubusercontent.com/44094559/55239117-63dca300-520c-11e9-90c8-e6dc2168bcbd.png)
