### ISSUE TITLE
Make a Pokenav Pokedex Api available 

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#308]
Being able to get access to the dex informations outside of Discord for 3rd-party developers would help much on developing new and custom features. This would be much cleaner that requesting and parsing pokenav bot through Discord.

"Edit" : Adding to that, things that would be really helpful in that API :
- Pretty much everything in the dex and counters command (including cp ranges for boss)
- A Shiny tag like in the dex but also for counters information (shiny possibility in raids)
- The weather that boost the pokemon /boss

**Comment by dandesousa** [comment]
I could certainly do the follow, but I probably cannot expose the counters details. That fails within Pokebattlers API and you would likely have to ask them to get the counters. I don't want to republish their data in that manner.

**Comment by Qualibert** [comment]
I contacted them about the counters, thank for pointing it out!
