### ISSUE TITLE
Allowing other roles to hand out badges. 

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#310]
**Is your feature request related to a problem? Please describe.**
Currently the only people able to hand out badges are server admins. We have certain players that are "Gym Leaders" who have their own assigned badge to hand out. However because these people aren't necessarily admins, they can't hand out the badges themselves and have to ask an admin to hand out the badge when someone deserves one. 

**Describe the solution you'd like**
I'd like to be able to give a larger group the rights to assign badges (e.g. gym leaders) ... but these players are not necessarily admins.

**Describe alternatives you've considered**
No alternatives available. 

**Additional context**

**Comment by daadyrbarn** [comment]
Yes please! A moderator role for badges and the option to set a different channel for badge config.

**Comment by dandesousa** [comment]
See the referenced issue above, consolidating tickets.
