### ISSUE TITLE
Leverage PokeBattler API For Bootstrapping New Bosses

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#320]
**Is your feature request related to a problem? Please describe.**

PokeBattler / Celandro has given us the 👍 to use their API for determining new raid bosses.

Currently the bosses are marked at a certain level. We should use their API to do the following:

1. Provide a whitelist for the purposes of requesting counters not in PokeNav's raid boss list
2. Offline script for bootstrapping raid bosses to alleviate manual updates

Related To:
#239 

We will be able to use their API to help with auto setting the boss, though the commands for doing so will likely be broken into a new ticket.

**Comment by Velocitractor00** [comment]
yus, this is awesome

**Comment by dandesousa** [comment]
Bootstrapping should be complete, so raid boss updates will be more timely and less work on my end. Will still require a manual update #239 and other tickets will result in more follow up tasks
