### ISSUE TITLE
Avoid duplicates does not work when gym has conflicting names

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#321]
When multiple screenshots are posted of an egg or raid at a gym that has a conflicting name (such as Starbucks), new channels will be created when avoiding duplicates is turned on. It does not seem to matter whether or not $gym is used to disambiguate the location.

There are a few possible solutions:

First is related to #150 . The prompt would likely need to come before the channel is created. If there is a match, assign the user to the channel already created.

Second possibility relies on an assumption. If the hatch/despawn time is within +/- x minutes, assume that the raid is the same. It is improbable that two gyms with the same name have the same egg/boss near the same time. Granted, this is not quite impossible, but the solution is automatic and will save coordination headache >99% of the time

Third, for ex raids only, there is extra info. Scanning the city may or may not be enough to disambiguate. Even if not, comparing times may also be enough to disambiguate these as well.

Side note: currently, there is no way for a user to disambiguate a gym without having to click on directions.

**Comment by dandesousa** [comment]
#289 for the disambiguation thing -- its been requested.

I think this would be a good idea to try out, and if it is effective for those using it -- expand as a default to everyone else. 

EX pass is tricky -- I know for us, we have at least 2 Starbucks gyms that hit pretty frequently.

**Comment by Kdog0073** [comment]
Actually, I just opened #323 too which could either be a supplement or an alternate to #289 

For ex passes, even applying the same solution (first or second that I mentioned) can work well. It may even simplify things on the back end to have such similar behavior. I just recall a couple of weeks ago the nightmare when both nearby Starbucks received EX raids and several people posted their invites at the same time.
