### ISSUE TITLE
Assume ultra friend for raid-counters. 

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#324]
Currently $c gives the pokebattler counters for level 30 attackers and no friendship bonus. It seems natural to assume ultra friends bonus instead. 

The change is relevant for Dialga because it switches the reported top counter from Breloom to Machamp.

**Comment by daadyrbarn** [comment]
I see the reasoning behind this, but would love for $mc to retain the default of no friends bonus. Adding an optional argument for friendship level would also work.
