### ISSUE TITLE
Fixing Localized EX Raid Gym tag in screenshots

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#332]
**Describe the bug**
Some screenshots have localized versions of the EX Raid tag which fail to be cleaned up.

This ticket covers two things:?

1.) Remaining languages that need to be cleaned up
2.) Gym names where the blends with the gym name and gets appended (we'd like to strip this from the name)

**Comment by TheGerontocracy** [comment]
Japanese:
![image0](https://user-images.githubusercontent.com/46009436/54191355-0a5b4100-44b6-11e9-9132-5ae3c1b1bb47.png)
![image1](https://user-images.githubusercontent.com/46009436/54191401-20690180-44b6-11e9-8f70-29f402b33ea0.png)

**Comment by mikelandzelo173** [comment]
Here are some label translations as seen in the game:
**English:** EX RAID GYM
**German:** EX-RAID-ARENA
**French:** ARÈNE DE RAID EX
**Spanish:** GIMNASIO DE INCURSIONES EX
**Italian:** PALESTRA RAID EX

There sometimes is a "SPONSORED" label there too. Could this also be a problem? Here are the official label translations as seen in the game:
**English:** SPONSORED
**German:** GESPONSERT
**French:** SPONSORISÉ
**Spanish:** PATROCINADO
**Italian:** SPONSORIZZATO

**Comment by dandesousa** [comment]
@TheGerontocracy any chance you can get me the text for those characters in the message

**Comment by mikelandzelo173** [comment]
@dandesousa here you are: 特別なレイドバトル

**Comment by Rhendak** [comment]
![Screenshot_20190315-114309_Pokemon_GO](https://user-images.githubusercontent.com/1855295/54449017-6be90d00-474d-11e9-826b-7b571f681010.jpg)
