### ISSUE TITLE
Ability to toggle off "Channel is about to expire" message

### ISSUE THREAD

**Issue by daadyrbarn** [PokeNavBot/issue-tracker#336]
We tend to use separate raid chat channels to coordinate raid routes etc., so we don't really have a need to extend raid-channels ever. Instead the message is just an extra notification/unread indicator that needs to be ignored. 

Would it be possible to add a `$toggle raid-expire-message`, or does it have a different purpose I'm not seeing?

**Comment by dandesousa** [comment]
This should be doable
