### ISSUE TITLE
Treat apostrophes as equivalent

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#338]
Picture attached. The gym is aliased as "sam's water tower". User typing in "Sam's water tower" appears not to work.

![image](https://user-images.githubusercontent.com/6502797/54647001-ea57ee80-4a6e-11e9-840e-800446965887.png)

**Comment by daadyrbarn** [comment]
looks more like a wrong apostrophe :)

**Comment by Kdog0073** [comment]
Welp, the "case" of the apostrophe then :D
