### ISSUE TITLE
Update Deoxys EX Speed/Defense/Attack images 

### ISSUE THREAD

**Issue by johnnyewton** [PokeNavBot/issue-tracker#342]
All four Deoxys image URL's lead to the same image even though the artwork for the other three forms seems to exist. Just curious if this was an easy fix?

https://static.pokenavbot.com/imgs/pokemon-icons/png/128/386-deoxys-defense.png
https://static.pokenavbot.com/imgs/pokemon-icons/png/128/386-deoxys-attack.png
https://static.pokenavbot.com/imgs/pokemon-icons/png/128/386-deoxys-speed.png
https://static.pokenavbot.com/imgs/pokemon-icons/png/128/386-deoxys.png

https://media.discordapp.net/attachments/428184932884545546/560171911808548865/386-deoxys-defense3x.png
https://media.discordapp.net/attachments/428184932884545546/560172030243242006/386-deoxys-attack3x.png
https://media.discordapp.net/attachments/428184932884545546/560172054998024222/386-deoxys-speed3x.png

**Comment by dandesousa** [comment]
Easy fix, artwork wasn't available before

**Comment by dandesousa** [comment]
Updated next bot / cache update
