### ISSUE TITLE
Exclude bots from leaderboards

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#349]
**Is your feature request related to a problem? Please describe.**
Raids and quests reported by bots are currently counted for the leaderboards. It would be natural to exclude bots from these rankings. 

**Describe the solution you'd like**
Modify the database query used for the leaderboards to exclude bots. (WHERE bot = false) 

**Additional context**
We source some high quality quests from a scanner-map and have a bot report these to pokenav to make sure pgmap is the best source for quest information. The coverage of the scanner is (luckily) incomplete, so user reports are still valuable.

**Comment by dandesousa** [comment]
May tie this with a general leaderboard blacklisting feature. That level of discord metadata isn’t actually tied into the database. Ill think it over.
