### ISSUE TITLE
Channel name does not get corrected when gym name is corrected

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#350]
**Describe the bug**
Our famous gym "Veendam City Council"  often gets misread and recognized as 3 random letters. When I then correct this gym's name through the bot's DM function with :tools: and someone signs up for the raid, the channel name is still called t5-bel-631 for examle. Important addition to this context is that neither raids had created channels before their name was corrected through the bots :tools: function.

**To Reproduce**
See screenshot step by step guide below. 

**Expected behavior**
For the channel name to have the same name as the corrected gymname. 

**Screenshots**
Original screenshot of the raid that's submitted.
![111](https://user-images.githubusercontent.com/1855295/55280111-5ebd4800-5321-11e9-92ce-1e76832d891a.png)

Raid is announced and gets recognized incorrectly.
![Screenshot_1](https://user-images.githubusercontent.com/1855295/55280116-6f6dbe00-5321-11e9-91c0-fd658cbe8d19.png)

Gymname is corrected through the bot DM function with :tools:. 
![Screenshot_2](https://user-images.githubusercontent.com/1855295/55280121-7c8aad00-5321-11e9-982d-83b15cb78b3c.png)

You can see that the gym name was correctly changed. 
![Screenshot_3](https://user-images.githubusercontent.com/1855295/55280139-ae037880-5321-11e9-9200-5c79e501d8fc.png)

When signing up for the raid a channel is created with the previously incorrectly recognized name of the gym.
![Screenshot_4](https://user-images.githubusercontent.com/1855295/55280135-9b893f00-5321-11e9-9746-c704df92ec37.png)

You can see in the raid's channel that the name of the gym is set correctly but the channel name does not match. 
![Screenshot_5](https://user-images.githubusercontent.com/1855295/55280146-b78ce080-5321-11e9-9918-0b67427146e0.png)

When the raid has ended (in this case done with `$end` but also when the raid end normally) the Gym name is then changed back to the previous incorrectly recognized name in the `announce-raids-here` channel.
![Screenshot_6](https://user-images.githubusercontent.com/1855295/55280158-c7a4c000-5321-11e9-9550-6c78bf397e07.png)

**Smartphone (please complete the following information):**
Not related. 

**Additional context**

**Comment by dandesousa** [comment]
Yup, this bug has been reproduced will be fixed tonight.

**Comment by dandesousa** [comment]
On end still shows original name
