### ISSUE TITLE
Make $raid and $boss command respond to local pokemon names. 

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#352]
**Is your feature request related to a problem? Please describe.**
My server's language is set to French (fra), meaning my users can report quests using both French and English pokemon names. It's somewhat confussing that French names don't work for the $raid or $boss commands.

**Describe the solution you'd like**
$raid and $boss should accept both local and English pokemon names.

**Comment by dandesousa** [comment]
Duplicate of #134
