### ISSUE TITLE
Strip punctuation from role names

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/issue-tracker#356]
**Is your feature request related to a problem? Please describe.**
I have a bot with a custom $starting command that mentions the raid's role. It does this by getting the channel name. However channel names do not have any punctuation where as role names can. This prevents the bot from successfully finding the raid's role name based on the channel name.

Examples:
Channel Name: caterpie-st-matthews-roman-975
Role Name: caterpie-st.-matthew's-roman-975

Channel Name: caterpie-st-mary-queen-773
Role Name: caterpie-st.-mary-queen-773

In the above examples, the period and apostrophe are not present in the channel name. 

**Describe the solution you'd like**
Remove punctuation from roles names so they match the name of the channel.

**Comment by dandesousa** [comment]
Will be extending the sanitizer for channel / role names to include `.`, `,` and `'`. I don't see which characters are explicitly allowed in channels names by discord so it might be a little trial and error in case you encounter any more. They do allow non-latin characters. I'll follow up if more information becomes available.
