### ISSUE TITLE
Stop choice dialog, choices are flipped

### ISSUE THREAD

**Issue by Darr247** [PokeNavBot/issue-tracker#364]
**Describe the bug**

When I run 
**$si blue star memorial**
multiple stops in this area are found, so the choice dialog is produced.
But when I choose #1, 2's info is displayed; when I tap 2, the info for choice 1 is displayed. 

**To Reproduce**
1. set Pokenav center at 42.524, -84.522 with radius of 15Km
2. Run $si blue star memorial
3. Select choice 1

**Expected behavior**
Expect choice 1's info to be displayed

**Screenshots**

**Mobile OS (if specific to your device):**
 - OS: Android and Win10 Pro
![MultiStop](https://user-images.githubusercontent.com/1146636/56080627-6f65c780-5dd1-11e9-9f24-4eba1d067cce.png)

![MultiStopBug](https://user-images.githubusercontent.com/1146636/56080604-244bb480-5dd1-11e9-8119-8c52e5b3703c.png)

**Comment by dandesousa** [comment]
This cannot be reproduced @Darr247 I have set the location of the pokenav server to this, we should follow up in #support and try to reproduce it
