### ISSUE TITLE
Allow raid time input to be in 12 hour time format

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/issue-tracker#365]
**Is your feature request related to a problem? Please describe.**
Ex raids already allows for raid time to be entered as a 12 hour time format (3:00 pm). It could be helpful to allow members to report raid times in the same way. Sometimes I remember what time a raid hatches/ends, but not how many minutes are left.

**Comment by collinguest** [comment]
Please please please do this. It works a lot easier for a lot of people

**Comment by planetrocky** [comment]
24 hour time format please (ISO 8601)

**Comment by dandesousa** [comment]
bump

**Comment by collinguest** [comment]
bump
