### ISSUE TITLE
Add partial matches as a fallback for POIs

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#367]
**Problems**
Often, OCR misreads the gym name by only a few characters. I used a custom bot for about a few weeks now that process PokeNav invalid raids by using Levenshtein distance to find the closest valid POI in a exported gym database. The results are very promising.
![2](https://user-images.githubusercontent.com/44094559/56312665-af54e380-611e-11e9-82b7-af36afe78aff.png)

At the moment, it's only helping correcting the raids by giving the correct name and adding the wrong one as an alias. We quickly reached the aliases limit of 10 on certain POI (names with dots or ex-tag are the worst) so that is not a great solution.

**Solution**
If PokeNav could use Levenshtein distance as a third fallback (Unverified POI > Verified POI > Aliases > Levenshtein), OCR errors could be greatly reduces, especially on Ex-tagged gyms.

Some customization could further help admins with fixing problematic POI (like enable or disable Levenshtein/custom distance on certains POIs),

Some filtering I'm using, avoid matching on:
- Too short reading (3 characters or less)
- Timer (Start with 0: and is 7 characters long)
- Only the ''ex-tag''

**Those issues could be related to that request:**
#151   `$gym` command to include troubleshooting advice
#150 When Gym is not able to be matched, have the first set of messages include a prompt for someone to update the location
#108 Enhanced Multi-Line EX Raid Pass Support
#338 Treat apostrophes as equivalent

**Filtering**
#357 Gym name should *never* be "Walk closer to interact with this Gym."

**Comment by BHollowell** [comment]
This would be quite helpful for me. I report a lot of raids from a PokeMap to help my small community stay in the loop even during light play hours. Not all of those gyms have their names listed, so I have to check the name of the location on Google Maps and hope that I can guess the name of the Gym in PoGo. I sometimes wonder if I'm creating duplicate POIs simply by not knowing the exact gym name.
