### ISSUE TITLE
Level 40 role provision 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/issue-tracker#370]
**Is your feature request related to a problem? Please describe.**
as people join they are stetting their XP manually in the trainer-profile channel, and then we are manually giving them a level 40 role 

this is true of a few servers I admin atm, even the ones without a trainer-profile channel, we go through the screenshots of team-assignment and grant the role

**Describe the solution you'd like**
I would like it if the XP is set by the user, and is above the 20 mill for level 40, they are automatically given the server role to accompany

**Describe alternatives you've considered**
I think the only other alt would be to read the lack of an xp bar from the avatar screenshots, but I assume that would be an OCR request and inherent costs.

**Additional context**
n/a

**Comment by Qualibert** [comment]
I would add that having a customizable threashold for at least one role could open up this suggestion to more people. 

For my part, I don't have a need for a level 40 role but I could use a level 30 role for reporting wild spawns for example!
