### ISSUE TITLE
Castform Pokedex Entry Wrong Movesets

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#372]
The $dex cast form entry should be the same as $dex castform-normal 

currently its populated with the wrong movesets

**Comment by mikosoby** [comment]
This issue is still bugged and needs fixing.
It doesn't matter what form you choose you will still receive the output with all the possible movesets for all the forms. Also the pkmn type is incorrect, and that goes together with it's vunerabilities/resistances.
