### ISSUE TITLE
Option to opt out of verified POI

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#375]
**Is your feature request related to a problem? Please describe.**
Yes, currently our Gym/Pokéstop count is inaccurate due to outdated verified POI data, due to these being removed or becoming a gym.

**Describe the solution you'd like**
An option to opt out of using verified POI.

**Describe alternatives you've considered**
No alternatives possible

**Additional context**

**Comment by typographynerd** [comment]
Does this mean that this had been done? This is something that is going to become more relevant as our community is starting to submit a lot of deletions/edits of old POIs. It will only get even more important when they roll out editing in the PoGO app.
