### ISSUE TITLE
Toggle remove date redundancy in raid announcements

### ISSUE THREAD

**Issue by Hasensuppe** [PokeNavBot/issue-tracker#376]
**Is your feature request related to a problem? Please describe.**
Raid announcements display date multiple times which is redundant. Raids only take place the day they're announced (only talking about raids here, not ex-raids!).

**Describe the solution you'd like**
Toggle remove date from created, hatches/hatched, despawns, expires, so date is still shown in title and bottom line of announcements. This may lead to grasp the important information faster.

**Describe alternatives you've considered**
Keep things how they are.

**Comment by dandesousa** [comment]
This was actually implemented such that expires and despawn no longer appears if the same and created was removed
