### ISSUE TITLE
`$help list` missing the `ex` subcommand

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#381]
**Describe the bug**
Using the **help** feature for the `list` command doesn't list the `ex` as a valid argument/subcommand. However this is a valid subcommand and should be listed here.

**To Reproduce**
1. Go to a channel where PokeNav commands are accepted.
2. Write `$help list`.
3. Check the output.

**Expected behavior**
The output should contain information regarding the `ex` option.

**Screenshots**
![image](https://user-images.githubusercontent.com/31369952/57580470-4573f380-74aa-11e9-9e09-a20395420454.png)

**Additional context**
All that is needed is this text:
```
**ex**
`Shows all active EX raids in the current server.`
```

**Comment by dandesousa** [comment]
The reason its not listed is actually because its just an alias for raids, which I support separating for clarity
