### ISSUE TITLE
Inconsistent ex pass scan

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#387]
![GitHawk Upload by dandesousa](https://i.imgur.com/8I8SXJK.jpg)

**Comment by sunkast** [comment]
![image](https://user-images.githubusercontent.com/4213265/62162304-f3db4800-b2e5-11e9-9854-d0fc55218a99.png)
via Discord user KayTV#8423

**Comment by dandesousa** [comment]
I believe these were fixed with the experimental scanner
