### ISSUE TITLE
$toggle raid-screenshots command should not disable research channels

### ISSUE THREAD

**Issue by wyccad915** [PokeNavBot/issue-tracker#390]
I run PokeNav on a server that uses Miscord. I have my Miscord linked channels as raid lobbies. At night there is sometimes non-raid related material in these channels, so I have another bot with admin privileges issue the command at the start and end of raids.

I have noticed that once I turn off raid screenshots, PokeNav does not work in my research channel. And when raid screenshots are turned back on, all is normal again. 

As the title suggests, if at all possible, I would like the ability to turn off raid screenshots, but leave research screenshots enabled.

**Comment by Qualibert** [comment]
$toggle raid-screenshots = If toggled off, image uploads are completely ignored in your server.
It's misleading I agree, it should be $toggle allow-screenshots maybe.

May I suggest using: 
$toggle allow-bot-screenshots = Toggles whether PokeNav reads screenshots from other bots.
or
$toggle raid-lobby #channel = Enable / disables raid announcements.

Meanwhile?

**Comment by wyccad915** [comment]
Thanks! I do understand it pretty much that way, and I really appreciate the suggestions. I'll have to give that a try.

**Comment by dandesousa** [comment]
Yeah technically it should be renamed its a toggle read screenshots feature
