### ISSUE TITLE
Quota history

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#391]
**Describe the solution you'd like**
Get some information regarding the server Quota usage for the server for last month(s).

**Describe alternatives you've considered**
Report the current server Quota just before clearing it at the start of the month. *I think this wouldn't be an effective solution.*

**Additional context**
As discussed on Discord, there are some information regarding the Quota, that are stored per server, but there just isn't a way to bring it up. A simple command that will print this information would be helpful.

**Comment by M3G4N5** [comment]
A general server status report at the end of each month would be great. Quota usage, activity stats, average raids posted per user, count of new joins, count of departed users, Server growth % (+/-) would be amazing!

**Comment by M3G4N5** [comment]
Bump

**Comment by dandesousa** [comment]
<img width="467" alt="Screen Shot 2020-02-03 at 6 37 45 AM" src="https://user-images.githubusercontent.com/3880281/73650260-bcac7180-464f-11ea-9d27-e371ca75a66a.png">
<img width="524" alt="Screen Shot 2020-02-03 at 6 37 51 AM" src="https://user-images.githubusercontent.com/3880281/73650261-bcac7180-464f-11ea-854e-eb6400bcca46.png">

**Comment by dandesousa** [comment]
think non-quota stats are out of scope for this one @M3G4N5 but happy to implement something different. Robust stats might be a bit of extra work.
