### ISSUE TITLE
$here command is repetitive

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#397]
**Describe the bug**
While you are in the dedicated Raid channel, the `here` command can be used again and again and it always indicates that you arrived.

**To Reproduce**
1. Enter a Raid channel.
2. Type `here`
3. Type `here` again
4. See the screenshot below

**Expected behavior**
I think it might be better to just give the `:ok_hand:` reaction or something *less spamy* to occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/31369952/58870035-ab295900-86bf-11e9-87e4-eff4657c2324.png)

*Btw the guy in the screenshot tried this on purpose.*

**Comment by Hasensuppe** [comment]
Why would you enter "here" multiple times?
