### ISSUE TITLE
Extend the $research syntax for counts of item rewards

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#399]
**Is your feature request related to a problem? Please describe.**
In my community many people report item rewards with using multiple ways `"3 rare candy"`, `"3x rare candy"` and so on. The solution could be to accept multiple ways of submitting the counts.
This might help with things in https://github.com/PokeNavBot/issue-tracker/issues/311 too.

**Describe the solution you'd like**
Extend the syntax so that these:
- `3 rare candy`
- `3x rare candy`
- `x3 rare candy`
- `rare candy 3`
- `rare candy 3x`
- `rare candy x3`
would all be accepted as `3 rare candy`.

Of course, this should be valid for all possible *item rewards*.

**Describe alternatives you've considered**
Not sure how problematic this will be, but it might be enough to just accept the first three options *(count as the first word in the string)*.

**Comment by daadyrbarn** [comment]
Might I add: it should also accept "3 rare"v:-)

**Comment by mikosoby** [comment]
> Might I add: it should also accept "3 rare" :-)

Not sure if `rare` is supported as a [reward alias](https://docs.pokenavbot.com/research.html#reward-aliases).

**Comment by daadyrbarn** [comment]
Would also just make more sense to accept the syntax "stardust x1000" since that's the way PokeNav displays it in the output.

**Comment by mikosoby** [comment]
> Would also just make more sense to accept the syntax "stardust x1000" since that's the way PokeNav displays it in the output.

All of this was meant to support every supported rewards *(except Pokémon)*. So just substitute `rare candy` in my examples with `pinap berry`, `stardust`, `silver pinap`, `golden razz`, `potion` and so on...

**Comment by dandesousa** [comment]
bump

**Comment by mikosoby** [comment]
bump
