### ISSUE TITLE
command to reset all leaderboards at once. 

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#401]
**Is your feature request related to a problem? Please describe.**
Currently when wanting to reset the entire `$top` leaderboard, you need to reset it part by part. This is very time consuming when wanting to reset the entire leaderboard. 

```
$reset-leaderboard research-reported
$reset-leaderboard raids-created
$reset-leaderboard raids-reported
$reset-leaderboard raids-joined
```

**Describe the solution you'd like**
A command to reset the entire leaderboards at once. For examle `$reset-leaderboard all`

**Describe alternatives you've considered**
No alternatives available.

**Additional context**

**Comment by dandesousa** [comment]
This is going to come in the release tonight, `$reset-leaderboard` with no argument will reset all so it will hopefully by the default behavior for people .
