### ISSUE TITLE
Support for Pokemon names in Other Languages (Dex entries 387+)

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#402]
**Is your feature request related to a problem? Please describe.**
Pokenav responds to French and German Pokemon names for raids and quests up to dex entry 386 (Hoenn), but not those with entries 387+. This causes confussion for those of my players reporting in French. 

**Additional context**
https://docs.google.com/spreadsheets/d/1EAJtwksJZBi3if5R--pWLbGHADgv8Xls9CnfYO2j1lM/edit#gid=0. The JSON files linked for issue 76 provide the same data except that Meltan and Melmetal is missing.

**Comment by dandesousa** [comment]
This should be done, alola forms shipping tonight
