### ISSUE TITLE
Re-enable raid announcements from other discord bots

### ISSUE THREAD

**Issue by c4nnu** [PokeNavBot/issue-tracker#404]
Hi,

Our small community has a bot that translates WhatsApp raid images to Discord and announces them to PokeNav. Community is still bit divided WA/Discord.

![image](https://user-images.githubusercontent.com/44108580/59972559-d35af800-9599-11e9-8cb0-178aabfbff9d.png)

This seem to be no longer possible after the PokeNav v1.51.X update made in 22/23 June 2019.

Is this "feature" something that could be re-enabled? Would very much appreciate it. Thank you.

**Comment by SpinDORK** [comment]
This would be good as we're currently working on Discord to Telegram and Discord to WhatsApp bots and bridges.

**Comment by dandesousa** [comment]
This was a bug and fixed this morning at 6am EST. If you are seeing otherwise please reopen or ping in support
