### ISSUE TITLE
PokeNav Category Seperation

### ISSUE THREAD

**Issue by SpinDORK** [PokeNavBot/issue-tracker#415]
**Our server splits areas via Category, eg; Northumberland, Tyne North & Tyne South**
Our server covers a large area and we use tags to notify of rare Pokémon or Raids like @Chansey, to make sure this didn't effect users miles away in Northumberland, we decided to split the areas based on ease of travel, so Northumberland is seperate from Tyne North which is seperate from Tyne South, currently we only have PokeNav in Tyne North and can't roll the bot out due to Category split.

**Describe the solution you'd like**
For PokeNav to recognise Channel split and allow for "unique" active Raids channels, so each Category has Active Raids and Announce Raids here and will post to that Categories representative channel.

**Currently we have to use the inferior DeliBot in Tyne South and Northumberland**
The other categories (Northumberland and Tyne South) are using the inferior DeliBot bot which is similar to PokeNav but requires the user to type out the commands to start a Raid instead of just posting a pic. Another alternative would be to push all channels together into one category but then we cannot have Active Raids as it would show for the full region and lose it's usefulness.

**How it would work**
Assign a channel Announce Raids Here 1, this would post to Active Raids 1 only. Assign a channel Announce Raids Here 2, this would post to Active Raids 2 only etc etc.

**Comment by dhwalden79** [comment]
I'm looking for a similar thing. I'd like people to be able to post the raid in the post raids channel then pokenav sort the raids into *levels instead of one active-raids channel.  This is because at it's peak our server can have 30 ongoing raids listed and people are not scrolling through and joining as there are too many raids in the active raids section.

if pokenav could sort it into 5*, 4* , 3* etc members would look through the smaller lists and actually use the raids channels as they are designed to be

**Comment by imadistack** [comment]
Our server is in the same boat. Too large to have 1 active raid channel.

**Comment by kentlowt** [comment]
We are in the same boat. Our city is divided into 21 areas each area has it's own raid rooms and needs its on channel or else no one will be able to find raids in the one channel.

**Comment by kentlowt** [comment]
I am interested in this as well. 21 channels posting raids is too much for a single category or a single active raids channel.

**Comment by daadyrbarn** [comment]
bump
