### ISSUE TITLE
Raid trains - Setup route in admin/different channel

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/issue-tracker#419]
**Is your feature request related to a problem? Please describe.**
Currently the only way to set up a raid train route and save it, is to create a raid train and make the route in the channel for this raid train.

**Describe the solution you'd like**
 I'd like to be able to create a raid-train route in the Pokénav admin channel or even better, a different specified channel (I have a dedicated channel named "bot-testing" for bot commands, so I don't bother other people with spammy messages). 

**Describe alternatives you've considered**
No alternatives available. 

**Additional context**

**Comment by BHollowell** [comment]
I'll +1 this. I set up a train for Entei today and it was a lot of spam in the raid train channel. I ended up deleting everything so that people joining the train didn't need to scroll through all those messages just to get to the info at the top.
