### ISSUE TITLE
Add support for shadow and purified in channels set as trade lobbies

### ISSUE THREAD

**Issue by enanox** [PokeNavBot/issue-tracker#423]
**Is your feature request related to a problem? Please describe.**
Shadow Pokémon can be traded and it offers a considerable amount of stardust + candy discount in power-ups / evolution / second moves after being Purified. Besides, it can help in rolling perfect IVs (or near perfect).
This request is a new feature that has arisen due to a new in-game feature. 

**Describe the solution you'd like**
Add `shadow` and `purified` to the input of `$want` and `$offer` commands, so they can be listed whenever a `$lucky` is triggered, or could be reacted to when `$offer`ed. Besides, they should be composed with existing keywords (like `lucky`)
E.g: 
- `$want shadow Lugia`
- `$offer shadow Bulbasaur`
- `$want shadow lucky Giratina-Origin`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dandesousa** [comment]
It looks like shadow Pokemon can no longer be traded -- purified pokemon will still be added though as a new trade modifier
