### ISSUE TITLE
Slowness Updating Research Rewards via DM in some Servers

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#424]
Some users report that updating research rewards are slow -- this is an investigation ticket with all relevant information.

**Comment by mikelandzelo173** [comment]
As requested I have tested updating rewards with multiple server settings (German as the default setting for our server and English). It doesn't really matter which language is set – it always takes about 60-80 seconds to update the reward. It also doesn't matter if the reward is written in English or German. This is permanent which means I can update a few rewards back to back without any speed improvements.

**Comment by dandesousa** [comment]
Looking into this at the moment. First steps to reproduce this on the PokeNav discord have failed it updates immediately

<img width="713" alt="Screen Shot 2019-08-04 at 1 57 33 PM" src="https://user-images.githubusercontent.com/3880281/62427360-08da2180-b6c0-11e9-99e5-7ba0ed9ed598.png">


Going to attempt using German as the language now.

**Comment by dandesousa** [comment]
Confirmed that the language is not solely responsible:

<img width="630" alt="Screen Shot 2019-08-04 at 2 02 04 PM" src="https://user-images.githubusercontent.com/3880281/62427393-7be39800-b6c0-11e9-87d7-2698d2c6f053.png">

**Comment by dandesousa** [comment]
@mikelandzelo173 can you confirm for me which region your discord server is in?

You can find this in your server settings

<img width="724" alt="Screen Shot 2019-08-04 at 2 03 32 PM" src="https://user-images.githubusercontent.com/3880281/62427413-aafa0980-b6c0-11e9-80ef-04d0b0d2858e.png">


Additionally -- does the poke stop or task update any faster?

**Comment by dandesousa** [comment]
FYI I did move a server to Western Europe and confirmed that it still updates <1 second, but I will try again in a bit -- maybe the move did not occur yet on that server.

Also, can you provide some details, like -- how many research reports are on the server when you do the update (ballpark is fine -- more than 10, more than 50, more than 100, etc)

Is it slow for you when you try to update a research report on the Pokenav discord server (report one there and try it out).

**Comment by swanny246** [comment]
@dandesousa I was one of the people reporting the issue, my server is set to Sydney as the server location. Not many research reports are posted when this occurs, I'd say less than 10.

**Comment by mikelandzelo173** [comment]
@dandesousa Our server is located in Central Europe. Slowness only applies to rewards/tasks. The Pokéstop updates immediately. It doesn't matter how many quests were posted. It's a problem with the very first one as well as the 20th one on that day. Tried it again right now with currently 8 reported quests. Took about 40 seconds this time.

**Comment by dandesousa** [comment]
@mikelandzelo173 I apologize there hasn't been much activity on this one -- have you been able to try to do a research report on the PokeNav discord and see if its also slow for you there?

If it is not, I might want to hope onto your server and try to report / update a research report. Simply trying to isolate if its something present for users in non-US East regions or if its server specific (since I'm unable to reproduce it by setting my guild region to match yours).

Please report back after creating a research report in the PokeNav discord and then updating it in a DM there. I'll follow up here or in discord with next steps.

**Comment by swanny246** [comment]
I just tested myself on the PokeNav Discord (based in Australia) and the
reward updated instantly. As of yesterday, I can confirm the slowness with
updating the rewards has still been occurring on my server though (server
location in Brisbane)

Would be happy to organise you access to my server if you want to test it
for yourself.

**Comment by mikelandzelo173** [comment]
@dandesousa I can confirm that changing a research reward on the PokéNav server has no issues at all. It works instantly. Changing a research reward on our local Discord Server however still has the known problems of delay.

**Comment by dandesousa** [comment]
@swanny246 Perhaps best to ping me on the PokeNav discord so I know who you are (evad3r?)

You can send me a friend request and perhaps I can try to reproduce it on your discord to ensure I see the same thing. I might need to introduce some diagnostics into the bot's next release if I can't figure it out but just seeing it happen and tracing through the code will go a long way.

**Comment by swanny246** [comment]
Guessed correctly! Yep I'm evad3r.

I sent you a friend request, I'll talk to you on Discord from there.

**Comment by dandesousa** [comment]
@swanny246 Just wanted to say thank you for letting me on your server, I was able to stare at the code for a while and discovered the issue.

cc: @mikelandzelo173 

There is currently a bug with the interactive logic, if you have clean research lobbies turned on -- PokeNav tries to delete your research reward message in a DM which is not allowed -- causing it to fail. However it does this silently after saving your last response, and eventually times out. This makes it seem like its really slow.

What actually happens is it records your response, then when it times out processes the last response it received as the update.

This is actually a typo on my end, which I never noticed because most servers don't enable this clean feature. 

I'll push out an update tonight to patch the issue. Apologies this took so long to track down.

**Comment by dandesousa** [comment]
this has been rolled out

**Comment by mikelandzelo173** [comment]
I can confirm that it works without any delay again. I'm glad we could figure it out. Thanks!
