### ISSUE TITLE
EX Raid Invite System

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#427]
We have started to see cases where people are offering EX raid invites or joining channels asking for invites. These messages often get buried.

What I would like to see is a way to display who has spare invites and who is looking for invites within the raid's embedded information. I imagine a set of commands like this:

EX Lobby
`$want-invite Gymname`
`$have-invite Gymname`
`$clear-invite Gymname` (resets want/have status)

Individual EX raid channel (the gym name is implied)
`$want-invite`
`$have-invite`
`$clear-invite` (resets want/have status)

**Comment by 01terrormoeder** [comment]
i like this idea!

**Comment by TheGerontocracy** [comment]
I've recently set up a custom match-making on my server that does this by reactions. The system is very simple. A bot maintains a list of users who can invite or want to be invited for each ex-raid reported. Users react with either ✉️ if they have an invitation to share and 🙏 if they would like to be invited. The bot updates the list  whenever one of these reactions are added or removed.

Signaling intent with reactions is cheaper than with commands and having a clickable list of users is convenient for initiating a conversation by DM. 

![IMG_7622](https://user-images.githubusercontent.com/46009436/69551480-1122d900-0f9d-11ea-977e-394a8bdd60b6.jpeg)
