### ISSUE TITLE
Only numbers on gym name second-line seems to break the OCR

### ISSUE THREAD

**Issue by Qualibert** [PokeNavBot/issue-tracker#434]
The timer and egg tier is not correct (get the screenshot as a placeholder), when using this screenshot:

![Screenshot_20190903-173740_Pokmon_GO](https://user-images.githubusercontent.com/44094559/64211777-39ef7280-ce75-11e9-9fbc-b3bf91a1b5a1.jpg)

It seems that blocking the second-line (which is 4 numbers) fixes the issue:

![2](https://user-images.githubusercontent.com/44094559/64211825-673c2080-ce75-11e9-9493-98a793efe5f7.png)

Even with an exact match on the POI name and different aliases, I was not able to fix it from within pokenav.

**Comment by dandesousa** [comment]
@Qualibert fixed this in my latest, sorry for the delay -- should be fixed tonight.
