### ISSUE TITLE
Alias Priority 

### ISSUE THREAD

**Issue by elprezjs** [PokeNavBot/issue-tracker#437]
I would like to be able to have an alias for a gym have priority over the regular name for the gym.  We have a number of gyms in our area that are named very similar and at least 2 that are exactly the same name we have developed nicknames for these gyms to tell them apart but it would be nice if those nicknames would automatically come up when you post a raid
Not sure it would be possible In the case of the 2 gyms named exactly the same as the screenshots would be the same but the ones that are close or ones that just are known more by their nicknames than the full gym name

**Comment by dandesousa** [comment]
To clarify, You want the alias to appear as the name of the gym in raid titles?

**Comment by elprezjs** [comment]
Yes that is correct

**Comment by dandesousa** [comment]
There can be many aliases potentially for one so a resolution order is an issue. Probably it would be a setting on the alias that overrides it as the default name.

**Comment by dandesousa** [comment]
duplicate
