### ISSUE TITLE
Split Active-Trades into "Offers" and "Wants"

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#438]
**Is your feature request related to a problem? Please describe.**
If many people submit their Want-/Offer- trades the `#active-trades` channel will be full of posts and without search or filtering possibilites  it is kinda easy to miss one want-trade in a lot of offer-trades so people get confused.

**Describe the solution you'd like**
Split the current `#active-trades` into `#active-want-trades` and `#active-offer-trades`.
> `#active-want-trades` will show only the **want-trades**
> `#active-offer-trades` will show only the **offer-trades**

**Describe alternatives you've considered**
Alternatives... maybe just changing the whole concept?
Like the `#active-trades` will have a **"want-list post"** and **"offer-list post"** for each player *(that has submitted something for trading)* and one will scroll between "player lists" not separate trades.

**Comment by LeRaffl** [comment]
Our community needs this!

**Comment by typographynerd** [comment]
This has been asked for in our community too.

**Comment by mikosoby** [comment]
bump

**Comment by LeRaffl** [comment]
Definitely bump up... I'd still like this

**Comment by LeRaffl** [comment]
I can also see it being implemented as a list for each Player... Like $stc works, just instead with a list of wants and offers

**Comment by LeRaffl** [comment]
Or maybe similar to $list q and $list r, so you would get a shortened version

**Comment by mikosoby** [comment]
bump

**Comment by mikosoby** [comment]
bump :(
