### ISSUE TITLE
Set server nickname based on profile

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#44]

**Comment by fortepc** [comment]
I'd love to be able to enforce a nickname policy and let the bot handle it like Hemlock does 
![image](https://user-images.githubusercontent.com/26149601/50609126-d30c5a80-0e9c-11e9-8a66-d1ca6289b35c.png)

**Comment by TheGerontocracy** [comment]
And for servers that don't enforce a nick-name policy, PokeNav could use the nicknames in the responses to $m and let users query players by nickname. This would open up a lot of cool possibilities.

**Comment by dandesousa** [comment]
See the more complete referenced issue above
