### ISSUE TITLE
Polish months

### ISSUE THREAD

**Issue by gc-017** [PokeNavBot/issue-tracker#441]
In the game months are in your native language. 
Date format is DD/MM/YYYY
Styczeń, Luty, Marzec, Kwiecień, Maj, Czerwiec, Lipiec, Sierpień, Wrzesień, Październik, Listopad, Grudzień.

Example: 21 Wrzesień, 1 Październik etc.

Time is 24h, example 11:28, 18:45 etc.

https://cdn.discordapp.com/attachments/579222168332795914/602436512541310996/Screenshot_2019-07-21-11-47-02-892_com.nianticlabs.pokemongo.png

**Comment by dandesousa** [comment]
Sorry this took so long, should be in the next release.
