### ISSUE TITLE
Add EX icon to Raid reports

### ISSUE THREAD

**Issue by typographynerd** [PokeNavBot/issue-tracker#447]
**Describe the solution you'd like**
Like was added to the raid train gyms, could the EX icon be added to EX eligible gyms when PokeNav reports raids in #active-raids. I thought this was requested some time ago but can't seem to find it. So I thought I'd put it back up on the radar.

**Comment by Rhendak** [comment]
It was suggested in #343 ;-)

**Comment by typographynerd** [comment]
Glad I wasn't losing my mind. I knew I saw it somewhere!
