### ISSUE TITLE
Server statistics to help admins gain better visibility into usage

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#448]

**Comment by Rhendak** [comment]
I'd really like two things for this:
- `$top` outputted to a specified channel at the end of the month.
- `$quota` send to all people who share quota with a server at the end of a month to give better insight on quota usage.

**Comment by dandesousa** [comment]
Statistics will likely be rolling updated. If you want a record you can probably tie in a scheduled command to another bot. Ill add some notes. To start the metrics will be able server usage with raids (to give visibility into the role creation thing) the expanded. I want to add better quota visibility too. Looking into the best way to expose this information

**Comment by dandesousa** [comment]
bump (this will be worked on)
