### ISSUE TITLE
Support for Slovak date-time in EX invitations

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#452]
**Is your feature request related to a problem? Please describe.**
Months in the Slovak language are not recognised so when a player posts a screenshot to create an EX Raid, nothing is created and we receive a 👎 from the bot.

**Describe the solution you'd like**
Please add the support for Slovak months and date format.

The Slovak date-time format on EX Invitations is `dd. month time_from_24h - time_to_24h `. E.g. `6. október 13:00 - 13:45` equals to `October 6 1:00 PM - 1:45 PM`.

**Months** *(EN - SK)*
- January = január
- February = február
- March = marec
- April = apríl
- May = máj
- Juny = jún
- July = júl
- August = august
- September = september
- October = október
- November = november
- December = december

**Screenshots**
Here are some screenshots that have been rejected by the bot.
![image](https://user-images.githubusercontent.com/31369952/66708874-1662f600-ed58-11e9-9354-4e5f3901c404.png)
![image](https://user-images.githubusercontent.com/31369952/66708877-25e23f00-ed58-11e9-8ed2-f527b26bb702.png)

**Comment by dandesousa** [comment]
Apologies for the delay here -- cleaning up the issues today and this will be in the next release (most likely tonight)
