### ISSUE TITLE
Auto-tagging for research reports (quests) 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/issue-tracker#453]
**Is your feature request related to a problem? Please describe.**
right now my server(s) stick with tagging the roles for quests, more than using the bot to report - I'd like to transition them over 

**Describe the solution you'd like**
much like the way we implemented auto-tagging for raids, where tagging was originally inside active-raids - I think it could work for research the same way 

**Describe alternatives you've considered**
I tried having people just update the research with one word reports, then having them tag the roles manually afterwards, but people just default back to the original method (tag only and aren't really using the bot to its full potential) 

**Additional context**
n/a

**Comment by dandesousa** [comment]
consolidating under a single issues #463
