### ISSUE TITLE
Default Active Raid Preset

### ISSUE THREAD

**Issue by KageGosuto** [PokeNavBot/issue-tracker#467]
Was wanting to see if there's a way to add a way to change the default preset active public raid names, like say someone uploads a t5 terrakion raid, instead of the channel that would normally pop up allow the admin to change its preset far beforehand to as a example t5-terrakion. Like a preset name list for each individual tier/pokemon channel that can be edited by the server owner/admins.

**Comment by dandesousa** [comment]
@KageGosuto 

maybe you can describe a bit a more. Give me some examples of things you would like to change (for example how it shows up now vs how you want it to appear. That would give me a better sense of the work involved and scope it out.
