### ISSUE TITLE
Toggle to show only raids with channels in active-raids.

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#468]
**Is your feature request related to a problem? Please describe.**
I'm struggling to show which raids are actively being organized, as opposed to simply being reported. My users, me included, tend to report also raids we do not plan to do ourselves. This is something I want, but it has the side-effect that active-raids contains raids nobody plans to join. I would like active-raids to only contain raids that are really "active". 

**Describe the solution you'd like**
A simple toggle such as `$toggle active-raids-with-channels-only` so that PokeNav posts to active-raids only after a channel has been created. You need to combine this setting with delayed raid-channels to get the desired effect. 

**Describe alternatives you've considered**

1. Use public raid channels. This was my old setup. The list of channels gives you an overview of where the action is, but it's a messy overview. Also I prefer to hide channels from users that don't need to see them. 
2. A possibility to condition on channel creation in raid notifications, as in `$create notify-rule active-raids-at-ex-gyms "ex_eligible: 1" "on-channel-create: 1"`. This would allow me to have the notifications channel function as a customized active-raids channel.

**Comment by dandesousa** [comment]
I'm open to implementing this feature to see how it works out.

**Comment by mikosoby** [comment]
Not sure if I understand what is meant by this suggestion. How should then people know about reported raids if they won't be shown in `#active-raids` channel?

**Comment by TheGerontocracy** [comment]
> Not sure if I understand what is meant by this suggestion. How should then people know about reported raids if they won't be shown in `#active-raids` channel?

It’s still shown in the raid-lobby where it is reported. At the moment, I have no active-raids channel on my server, but several raid lobbies. With clean raid lobbies, each of the raid lobbies gives a clean overview of reported raids of a particular category or area.

**Comment by mikosoby** [comment]
bump
