### ISSUE TITLE
Ability to blacklist gyms from raid reports

### ISSUE THREAD

**Issue by jesseelwell** [PokeNavBot/issue-tracker#469]
**Is your feature request related to a problem? Please describe.**
We have an area that was formerly a popular place to play that has asked our players not to return. We would like to blacklist the POIs in that area such that players attempting to report raids there cannot.

**Describe the solution you'd like**
A command to mark a POI as blacklisted. When a player attempts to report a raid at such a POI they instead receive an error message letting them know that they POI is blacklisted. Bonus points if the message could be customized.

**Describe alternatives you've considered**
As suggested we could simply use a POI note. We will try this in the meantime and see how effective it is.

**Additional context**

**Comment by kentlowt** [comment]
This would be good for those gated commercial sites that 95% of the people don't have access to. We have a few of those in our area as well.
