### ISSUE TITLE
Allow Notifications to Create Raid Channel (when auto-create channel is turned off)

### ISSUE THREAD

**Issue by Kdog0073** [PokeNavBot/issue-tracker#471]
When the option to create a channel automatically is turned off, the bust_in_silhouette emoji appears under the embed for the original post and the active raids channel. However, the emoji to create/join the channel does not appear for the notification/subscription messages.

The request of this ticket is to insert the emoji under a notification message while a raid is active so that people with certain subscriptions can create the channel directly from the message that notified them.

![image](https://user-images.githubusercontent.com/6502797/71329509-b329d880-24eb-11ea-92ff-bcfc3cd51415.png)

**Comment by dandesousa** [comment]
duplicate #451
