### ISSUE TITLE
Reaction emoji 

### ISSUE THREAD

**Issue by Loony2go** [PokeNavBot/issue-tracker#473]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Loony2go** [comment]
It really bothers me that people in my community cant seem to understand that by reacting to emoji they still need to find the channel in which they should be chatting in for the role channel they join by tapping emoji. I believe it would be great if by tapping emoji they were automatically taken into the appropriate chat channel. I have tried how to videos, contests, even recording an 8 year old kid figuring it out but the older people say the emoji is too small and having to take another step to look for channel they joined is too much. Maybe if the emoji were a brighter more obvious emoji color or if the emoji was bigger it would help when its a reaction emoji. Perhaps having the ability to allow some roles to react to emojis but not write at all in the channel would work?

**Comment by mikosoby** [comment]
1) Not sure if it is really allowed by the Discord.
2) After someone clicks on the 👤 he/she will be tagged, so there really should be no problem in finding anything.
3) Emojis aren't the same for every platform. PCs, Android or iOS all can have slightly different image for the same emoji.
4) You can create a role and disable writing to a specific channel by yourself. That has nothing to do with PokeNav or anykind of bot.

**Comment by dandesousa** [comment]
@mikosoby has pretty much answered all of these -- not possible for a discord bot -- limitation of discord.
