### ISSUE TITLE
Raid reporting and community teamwork

### ISSUE THREAD

**Issue by Loony2go** [PokeNavBot/issue-tracker#474]
**Is your feature request related to a problem? Please describe.**
Im frustrated because i cant get more people to report snapshots, yet they all take advantage of the reports that only about 10 members continue to put time and effort into. We like the app because it clearly shows us the order in which the raids expire and hatch unlike on discord where only a list of active raids without detail is shown. We want to use pokenav app,  but we want more people to help report raids. Weve tried contests, weve told them we pay for ss weve seen them online and at the raids without commenting or using discord and we dont think thats fair. We believe app access should be restricted to those who pay for the snapshots, this way they are more motivated to discuss on discord a plan or route in which to do alot of group raids.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dandesousa** [comment]
New feature development has been paused on the app pending the announcement in discord
