### ISSUE TITLE
Companions and raids reported

### ISSUE THREAD

**Issue by Loony2go** [PokeNavBot/issue-tracker#475]
**Is your feature request related to a problem? Please describe.**
Its confusingb
what is considered reported, joined, and created...and we feel like it would be better to count how many snapshots a person posts, how many they join with atleast 3 members at expiration, and how many raids a person updates post hatch for the raid boss. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Loony2go** [comment]
Oh and also definetly keep the research reported, and we would like to have nests reported as well.

**Comment by mikosoby** [comment]
![image](https://user-images.githubusercontent.com/31369952/71920444-0b690780-3187-11ea-99f1-af2a1c0b24c5.png)

**Comment by dandesousa** [comment]
You can ask this in the support channel as we can paste the link and get you a quicker response -- though I appreciate the creation of tickets for tracking change requests
