### ISSUE TITLE
Exclude raids at gyms with scheduled ex-raids from ex-raid notifications.

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/issue-tracker#477]
**Is your feature request related to a problem? Please describe.**
Gyms with scheduled ex-raids can now spawn raids, but completing such a raid will not result in  an ex-raid invite. You probably want ex-raid notifications to exclude such raids. 

**Describe the solution you'd like**
Automatically exclude raids at gyms with reported ex-raids from notification-rules containing "ex_eligible: 1".

**Comment by mikosoby** [comment]
I think it's a good idea but please implement a switch for this, because Niantic can likely change the behaviour.
