### ISSUE TITLE
2-colored offer/want trade system

### ISSUE THREAD

**Issue by Hedva** [PokeNavBot/issue-tracker#485]
**Is your feature request related to a problem? Please describe.**
It is not clear right now what trade is an offer and what trade is a want. It is hidden in the text, but people who don't read/write/speak English it is confusing. It would be much easier to see what type of trade it is at a glance, by using a 2 color system.

**Describe the solution you'd like**
I would like to see a 2 color system in the embed border for the trade offers/wants.
Green border - OFFER - Pokemon is available; so green.
Red border - WANT - Pokemon is not available; so red.

**Describe alternatives you've considered**
I thought about sepreate channels for offers and wants. But I don't feel there is a need for 2 separate channels. Because there are much more 'wants' then 'offers'. There are enough channels so we don't need an extra one.

**Additional context**
Example:
<img width="693" alt="offerwant" src="https://user-images.githubusercontent.com/2246965/76737520-38c6c880-6769-11ea-81d9-9589477435b3.PNG">

**Comment by mikosoby** [comment]
Still think that this - https://github.com/PokeNavBot/issue-tracker/issues/438 would be a better solution.

**Comment by Hedva** [comment]
> Still think that this - #438 would be a better solution.

I can imagine that's useful for big communities. But for more small communities like mine there is no need for more channels. It only generates an empty channel, because almost everyone uses $want and almost nobodies offers, because that's how it works apparently
