### ISSUE TITLE
Tournament Lobbies/Channel/Role Creation 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/Issue-Tracker#492]
**Is your feature request related to a problem? Please describe.**
I feel that this could be beneficial to many servers who host PvP 

**Describe the solution you'd like**
much like the current raid lobby system, I would like to try out a `$tournament` command system, this would take place in a designated pvp lobby, and be able to deal with different types of tournaments the way we deal with different types of raid boss - e.g. `$tournament forest` would produce a forest cup channel, with associated role and artwork 

**Describe alternatives you've considered**
at present I create all of this sort of stuff on the fly for a number of servers, but I think having it be a more temporary channel, with a tagable role, might encourage people to take it upon themselves to have live format tournaments - as well as allow for the creation of more wider community centred ones that could be managed and advertised easily within the channels

**Additional context**
I know that the events support has been much discussed, but I feel like this method of delivery for tournaments could almost double up as that - while using much of the same framework people are already familiar with for raids - it could go as far as to feed into the app or map setups, and show tournaments (although silph do already do this) 

anyway, I thought this was worth dropping in as a suggestion - as previously when I had thought about how the bot would handle pvp tournaments or events, it wasn't as similar an implementation to raids as this idea - take it easy, stay safe pips 

Tractor

**Comment by mikosoby** [comment]
bump
