### ISSUE TITLE
Recognise EX Raid Gym tag (only) in Chinese language

### ISSUE THREAD

**Issue by Derwan1** [PokeNavBot/Issue-Tracker#494]
Although PokeNav doesn't currently support the Chinese Language, it would be great if it could acknowledge the EX Raid Gym tag from the Chinese language so that it's not used as the gym name in reports.

See attached screenshots for reference.

![ChineseEXtag3](https://user-images.githubusercontent.com/67808672/86500225-0520b480-bdd3-11ea-8e2f-d6d213f5ba22.png)
![ChineseEXtag_report](https://user-images.githubusercontent.com/67808672/86500228-0fdb4980-bdd3-11ea-818c-9aa7012e1b77.png)
![ChineseEXtag](https://user-images.githubusercontent.com/67808672/86500230-110c7680-bdd3-11ea-85bd-9f05b79aae73.png)
![ChineseEXtag2](https://user-images.githubusercontent.com/67808672/86500239-2386b000-bdd3-11ea-8d7b-7570a9d5baba.png)
![ChineseEXtag5](https://user-images.githubusercontent.com/67808672/86500253-2f727200-bdd3-11ea-9d33-ffdcbf648aaa.png)
![ChineseEXtag4](https://user-images.githubusercontent.com/67808672/86500266-3ac59d80-bdd3-11ea-8020-dc69244e816f.png)

**Comment by dandesousa** [comment]
Can you provide the text above so that it can be copied so I don't get any of the characters wrong.

**Comment by Derwan1** [comment]
Here's the text that PokeNav picks up: VIP團體戰道館

I'm not Chinese myself so I have no idea what the characters mean.  Comparing them to the image, it looks like the correct characters.

**Comment by dandesousa** [comment]
Sorry for the delay this is going out tonight.
