### ISSUE TITLE
Individual Gym Sign Up on Raid Trains

### ISSUE THREAD

**Issue by DMS27** [PokeNavBot/Issue-Tracker#496]
Now that remote raiding is live (and soon raid invites will be) it is becoming more and more difficult to coordinate raid trains. The biggest issue is always knowing who is participating in what raids, as not everyone signed up will be doing the full raid train route.

I think it would be useful if (once the train route is set) people could sign up for individual gyms on the route as there are always people that can’t do the whole route and yet their name appears on every $m list for every subsequent gym on the route which means checking every time whether people are doing that particular gym or not (or whether they just haven't confirmed their attendance). If you're having to confirm every time that the people not present are in fact not raiding it relies on people being on their phone for the whole of raid hour, which isn't always possible.

Not sure how / if this would work but would make managing raid trains easier if each $m list was specific to each gym on the route, with a view to speed up the process of raid trains and hit more raids in the hour window.

**Comment by dandesousa** [comment]
I'm not sure how this would work honestly. Probably the complexity isn't something I will have time to deal with in the medium term.
