### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#521]
@IVpips idea:  the raid organizer can set up how many people are in the discord raid lobby 
however, I think it is important because there are players who can invite more players

https://cdn.discordapp.com/attachments/441032035524673536/741236989034102784/20200807_121100.jpg

**Comment by dandesousa** [comment]
You know that you can `$set max-raid-party-members` at a server level to restrict the number of people allowed?

**Comment by Roli0109** [comment]
i know but the raid lobby creator overwrites in your own lobby!
