### ISSUE TITLE
Support iPad screen resolutions for OCR

### ISSUE THREAD

**Issue by maconleary** [PokeNavBot/Issue-Tracker#522]
When users screenshot eggs at EX Raid gyms using their iPads, PokeNav tries to read the EX Raid tag instead of the actual gym name, typically misidentifying the gym as KRAID GYM.

If a moderator sees it, they'll fix the name with :tools: , but a moderator is not always around.

**Comment by dandesousa** [comment]
Can you post some example screenshots -- I can adjust the crop settings based on the resolution

**Comment by maconleary** [comment]
![newton](https://user-images.githubusercontent.com/50319611/89739252-2716f200-da77-11ea-906b-b62f1c4a28ea.png)
More to come later....

**Comment by maconleary** [comment]
![pvh](https://user-images.githubusercontent.com/50319611/89762269-020e9780-dae8-11ea-9f8f-0dbeb16a5c01.png)

**Comment by maconleary** [comment]
![sparrows](https://user-images.githubusercontent.com/50319611/89762363-2d918200-dae8-11ea-91d9-e60eb32138fd.png)

**Comment by maconleary** [comment]
![twh](https://user-images.githubusercontent.com/50319611/89762443-5d408a00-dae8-11ea-93e5-ddc1a92999e6.png)

**Comment by maconleary** [comment]
![sparrows](https://user-images.githubusercontent.com/50319611/89762553-90831900-dae8-11ea-9c5b-763099291587.png)

**Comment by maconleary** [comment]
Last 3 are all from the same device, unfortunately. Will try to get some more if I can

**Comment by maconleary** [comment]
![outdoor](https://user-images.githubusercontent.com/50319611/89770958-713fb800-daf7-11ea-836b-3c8c9e9622ed.png)

**Comment by FlickFire** [comment]
On this screenshot the issue is the first letter "A" that is not recognized. 
The gym is not Ex Raid eligible. 

![Aumonerie des étudiants](https://user-images.githubusercontent.com/62517446/89783936-136f9800-db18-11ea-8e7f-f92f7ee4ba2d.png)

**Comment by maconleary** [comment]
![FA2D0F61-D57E-4AFF-9D88-E22CD1352F3D](https://user-images.githubusercontent.com/50319611/89830380-f658ba80-db53-11ea-9799-91861391b64d.jpeg)

**Comment by maconleary** [comment]
![bowling](https://user-images.githubusercontent.com/50319611/89868790-4adb5480-dbab-11ea-85e0-62ae0d305a24.png)

**Comment by maconleary** [comment]
![shmc](https://user-images.githubusercontent.com/50319611/90242070-3ce43880-de24-11ea-8b4a-0af2796c5717.png)

**Comment by maconleary** [comment]
![eastcem](https://user-images.githubusercontent.com/50319611/90242237-86cd1e80-de24-11ea-9667-69c6438e335f.png)

**Comment by maconleary** [comment]
![roxchurch](https://user-images.githubusercontent.com/50319611/90249365-3a88db00-de32-11ea-812a-2c8963b59a24.png)
