### ISSUE TITLE
A dedicated Announce-Remote-Raids channel option 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/Issue-Tracker#524]
**Is your feature request related to a problem? Please describe.**
Remote Raids are increasing the stress on the bot, I think one way to avoid rate limits might be a specialised lobby channel, for reporting these remote raids on the remote raid only servers, but also on mixed servers this could be toggled 

**Describe the solution you'd like**
#announce-remote-raids channel which would function in much the same way as an existing announce raids channel, but with a few key/subtle differences: 

1) - the silhouette to join option would be disabled, it would be considered that only the host of the raid would be on-site, and that each additional person who joins, would require an invite by default. 

2) - the join message that remote raiders would receive in these raid channels, would reflect more of the information that is given on the 2nd red envelope reaction inside the existing raid channel structure - i.e. it would provide them with the hosts trainer code - the onus would be on them to add - and a ready message prompt would replace the here prompt - i.e. "say ready when you are good to go in" - this would stop the $gtc spam in remote raid lobbies - but it would also reduce the need for that 2nd reaction role to exist with the red envelope in the raid channel. - the invitees joining in this way, would also automatically be added to the go-command list for needing an invite (with no need for the host to manually do so) 

3) - as a side benefit to this, the terminology "ready" would become more widely used by remote raiders, and allow for the distinction between that as a command and "here" although at present they do the same thing i.e. add to the same total, it would benefit mixed lobbies to have a way of knowing who is who. 

**Describe alternatives you've considered**
its all a work in progress so far things are getting better with remote raids, but I feel that this designated announce lobby system, would prevent the larger servers out there that are dealing in global raid requests, from denying features/content to those smaller more localised servers 

**Additional context**
I dont think that the per-channel limit is always necessarily the way to go with remote only raids, but in the current setup you have 10 people join a hosts raid (thats already too many for 1 person to invite) so there is no distinction in the `go` or `backout` commands between those two (what I call groups) lobbies of invitees - I know the queue system has been discussed, but I think the next step would be to separate the users who join as they do so, by groups of 5 in order - allowing for `$go Group1` and `$go Group2` etc etc.

**Comment by LeRaffl** [comment]
Backing this up because of the suggestion to clean up a few Welcome messages when joining a raid. When remote raiding there are duplicates.

**Comment by dandesousa** [comment]
This has been implemented -- remote raid lobbies and special remote raid channels coming soon -- follow up features will be tracked separately.
