### ISSUE TITLE
$remote i @FredBloggs can be used to set FredBloggs to 'remote, no invite needed' against his wishes

### ISSUE THREAD

**Issue by maconleary** [PokeNavBot/Issue-Tracker#537]
**Describe the bug**
Users should have control of their onsite / remote / need invite status. $remote i @username can be used by anyone to reset it

**To Reproduce**
1. Join a raid with 🧧 
2. Ask someone else in the raid to type $remote i @YourUsername
3. Your status gets reset to 🌐 , the invite summary does not mention you as you no longer appear to need an invite
4. Anyone can do this - not just moderators or creators

**Expected behavior**
I don't think $remote i @username should do anything. At a pinch, it should set them to 'invite needed' only if used by a raid moderator, but I suspect it toggles it instead and it can be done by anyone.

**Comment by DMS27** [comment]
We believe that this is also the case with $onsite @username and $remote @username. These commands can both be used to change someone else's status.
