### ISSUE TITLE
More language

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#539]
For example: Hungary

**Comment by dandesousa** [comment]
Language for what? Bot translations? Pokemon names? Research?

**Comment by mikosoby** [comment]
Not sure about the author, but my community would appreciate a slovak localization. But there are no slovak pkmn names and other things, so just regular PokeNav strings.

**Comment by dandesousa** [comment]
This seems like a duplicate of #134
