### ISSUE TITLE
Invite free raids

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/Issue-Tracker#542]
**Is your feature request related to a problem? Please describe.**
I have the impression that some of my users prefer to raid only with only players on the spot and/or they are overwhelmed by the invite system. It would be good to shield them from pressure to invite others on discord. 

**Describe the solution you'd like**
Something along these lines could work: 

- A new server setting: `$toggle opt-in-invites`. 
Defaults to off, persisting current behaviour. 
- A new user setting: `$toggle allow-invites`. 
Defaults to off. People who actually likes to invite (like me) can toggle it to on. 
- A new command to open up raid to invites `$allow-invites` 
Allows players to add invites when backup is needed.

If a server has opt-in-invites toggled to off, raids would work like currently.  

Fresh regular raids on servers with opt-in-invites only allow joining per 👤. Pokenav opens up the raid to invitees and adds to 🧧 to the raid messsages when either (a) a member with allow-invitees toggled on joins or (b) a member opens the raid by saying $allow-invitees in the raid channel..

**Additional context**
![IMG_AF34798A5372-1](https://user-images.githubusercontent.com/46009436/93188465-47566280-f741-11ea-8017-c6b23176aa38.jpeg)

**Comment by typographynerd** [comment]
This is an excellent idea and would be very useful in our server, as we do mainly hybrid raids and very little of true remote raids. 

A few additional ideas: it would also be useful to have a count of available invites. This could be as simple as a counter (like team member counts, except that it counts down from 5 or from 10, if there are more than one person offering invites). It would also work with another suggested feature: an individual being able to set how many invites they have available (if they have already promised invites to others not in the channel)—similar idea to the `$with` command
