### ISSUE TITLE
Restrict allowed raid bosses in a server

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/Issue-Tracker#545]
* Restrict bosses allowed to be made to a list of bosses specified by admins
* Restrict bosses by tier 
* Restrict to the current `assumed-t5`

**Comment by definitivegear** [comment]
+1 to this!

**Comment by dandesousa** [comment]
All restrictions are per lobby and additive. No restrictions is the default — all are allowed. 



**To add a restriction to a specific lobby:**

`$create raid-boss-restriction #raid-lobby 5` 



**You can then add another restriction**

`$create raid-boss-restriction #raid-lobby timburr` 



**You can delete it using `$delete`: **

`$delete raid-boss-restriction #raid-lobby 5` 



**Or all restrictions with no arguments**

`$delete raid-boss-restriction #raid-lobby` 



**OPTIONS / QUESTIONS**

Should users be allowed to report eggs of the same tier as boss restrictions. I.e. if you have a mewtwo restriciton for a lobby, should users be allow to report tier 5 eggs?



Should users be allowed to change the boss to something that would violate the restriction? Pretty sure the answer is either **NO** or **DON’T CARE.**



How would you like to answer screenshots that are scanned — should they be rejected if they don’t conform? These would still consume quota.



How would you like to handle new bosses that might not exist in the database with a tier yet. I.e. if Niantic introduces or changes the tier of a Pokemon from never existing to a tier 3 but I haven’t yet updated the database to it being a tier 3 (typically I do this within a few hours of the rotation). Should “unknown” tiers be allowed or do you want to temporarily add these to the list until I fix it?

**Comment by definitivegear** [comment]
**All restrictions are per lobby and additive.**

In this case does "lobby" refer to main raid channel? I'm not sure what else it could mean but wanted to be sure.

`$create raid-boss-restriction #raid-lobby 5`

What does the "5" signify in this case?

Will there be the ability to add multiple bosses per channel? ie. #remote-tier-3 would have restrictions set to the current lineup of bosses available, compared to #remote-giratina which encompasses one specific boss. We would need to restrict a tier to multiple specific options.

**How would you like to handle new bosses that might not exist in the database with a tier yet.**

I don't mind needing to wait until the database is updated to create the restrictions - this feature is beneficial to tier 1 + 3 but it's main purpose (at least for me) is restricting tier 5 to one boss. The main issue we have is people creating raids for mewtwo, rayquaza, mew, etc, in #remote-giratina as a joke.

Curious: What will happen when someone tries to create a raid outside the restriction? Generic error message? Posting a list of acceptable bosses?

**Comment by dandesousa** [comment]
Raid lobby refers to the announce raids channel. In your case, #remote-giratina or whatever you setup. 

5 refers to a tier so you could restrict it to only pokemon known to be or expected to be tier 5 bosses. Or you can restrict it by the specific form. 

If they try to post something not in the list, it will post an error message that says you must specify one of the following bosses. 

Would it be useful to restrict a lobby to the current assumed-t5 or do you recreate channels every time there is a new boss?

**Comment by definitivegear** [comment]
Answers explain everything perfectly! Looks like it's exactly what we're hoping for.

We recycle the same tier 5 channel and just re-name it. The only concern I'd have in that case is when the next trio come out for example (Cobalion, Terrakion, Verizion) - we're going to have split channels for each initially, and then combine them once it dies down. How would assumed-t5 work in that case? 

When there's just one tier 5, assumed-t5 would work perfectly for setting the restriction to prevent the need in doing it manually.

**Comment by definitivegear** [comment]
To answer the other questions:

**Should users be allowed to report eggs of the same tier as boss restrictions.**

We don't really use reporting/eggs, so I may not be the best resource for that answer. I would assume that if mewtwo is the set restriction, the corresponding tier 5 egg would be mewtwo regardless, so eggs should still be allowed. The restriction is to prevent someone creating rayquaza in a mewtwo channel.

**Should users be allowed to change the boss to something that would violate the restriction?** 

Not many know how to do this anyways (we have so many "girantina" and "giritina" raids made), but I'd go with a solid no.

**How would you like to answer screenshots that are scanned — should they be rejected if they don’t conform? These would still consume quota.**

If someone uses their screenshot quota to post stuff that goes against a restriction, that's their own fault. They'll learn after the first time it's rejected.

**Comment by dandesousa** [comment]
When theres multiple bosses the assumed-t5 would basically be disabled. I would probably just allow any tier 5. Perhaps its best to leave this feature off for now and revisit it if necessary.

**Comment by definitivegear** [comment]
The entire feature or just the assumed-t5 part of it?

If we can set multiple raid boss restrictions per channel then it would alleviate the need to do it automatically, which is totally fine. I have no issue creating the restrictions manually, since I've started needing to do it for raid notifications now that we offer that.

**Comment by dandesousa** [comment]
sry just the assumed-t5 part
