### ISSUE TITLE
$bye reminder ping inside raid lobby

### ISSUE THREAD

**Issue by definitivegear** [PokeNavBot/Issue-Tracker#552]
**Is your feature request related to a problem? Please describe.**
It's tough to provide education to 25k people, with hundreds of new people each day. Sliding in subtle pieces of education could greatly improve familiarity with the bot

**Describe the solution you'd like**
A small message embed (doesn't need to be a ping) to the host inside the private raid lobby 5 minutes after it's been created with a reminder that says "make sure to close your lobby, type $bye"

**Additional context**
Issue #551 may be enough to not need this, but figured it was worth mentioning if it's a low level of effort and there's value in it

**Comment by dandesousa** [comment]
I don't think this is needed now you have shortened lobbies so will close it unless it comes up again
