### ISSUE TITLE
a command to disable people from raid organization for a while



### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#557]
$temp @mention time reason

For example 

$temp @roli0109 3d But i dont know

**Comment by sunkast** [comment]
A general purpose bot like Atlas that has a mute feature could handle this.

**Comment by Roli0109** [comment]
general bots are suitable for all server mute

**Comment by dandesousa** [comment]
@sunkast is right -- you should use a general bot and a custom mute role and you put that role on whatever channels you want -- the raid organization channels for example.
