### ISSUE TITLE
trade embeds - please re-introduce the plain text name in the header 

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/Issue-Tracker#560]
**Is your feature request related to a problem? Please describe.**
the trade embeds frequently misfire on the tagging of the user who sent them, appearing as either an error code or their ID - which both have varying degrees of un-usefulness 

**Describe the solution you'd like**
tag the sender of the trade request by plain text name in the header 

**Describe alternatives you've considered**
some of us know how to search by ID, and that the embeds might appear differently on PC or Mobile, but a higher % of users simply dont know that 

**Additional context**
N/a

**Comment by dandesousa** [comment]
This is going back to the embed containing the name of the user in the description with the tag in the title to allow for quick messaging when it does resolve.

**Comment by dandesousa** [comment]
<img width="644" alt="Screen Shot 2020-11-09 at 8 32 10 AM" src="https://user-images.githubusercontent.com/3880281/98547368-1177bb00-2266-11eb-86e1-7b89235febd3.png">
