### ISSUE TITLE
Restrict command

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#561]
a command that restricts access to only members whose basic 3 commands are set

 Basic commands:
- Set ign
- Set trainercode
- Set xp
-

**Comment by dandesousa** [comment]
Duplicate #139

**Comment by ninertwo** [comment]
I looked at the previous ticket and felt strongly enough to start an account. 
  The reason for this  request, ? To force new and transient remote trainers, who currently  disrupt  numerous servers and require them to comply . 
 Remote Raiding ( July 2020)and the test integration with Pokebattler ( Nov 2020) Our server has been inundated with trainers from other servers, pokebattler notifications, and other 3rd party raid boards. 
   They join, have no info set up, so now we the hosts have to stop everything their info. Adding injury to insult, most are transient members and leave right after the raid. So what did we get out of it? Time wasted and frayed nerves.  That’s why having the bot restrict brand new members to those commands is ingenious. Wanna raid? nope, you can only set up your profile so hurry!
