### ISSUE TITLE
quick start trainer command

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#565]
TYPE Q / A
Forexapmle:

Bot: what is your trainer code?
People: 7484838383839
Bot:what is your ign?
People: Miklós
Bot:in which country do you live
People: Hungary
Bot What is your favorite pokémon?
People: shiny girqtina
Bot: how much xp is there in total?
People 1000000009
The end

**Comment by dandesousa** [comment]
effectively implemented by `verify`
