### ISSUE TITLE
Do Not Update Member Counts After $go is used

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/Issue-Tracker#571]
Also do not clear reaction emojis 

This was requested by TheGeron -- will revisit it after queuing since it potentially changes the entire usage patterns.

**Comment by FlipsCat** [comment]
> Also do not clear reaction emojis
> 
> This was requested by TheGeron -- will revisit it after queuing since it potentially changes the entire usage patterns.

I am confused as to exactly what this means? after go unless you reset or they type $BYE it does not update nor unlock?

**Comment by dandesousa** [comment]
Honestly I can't remember this either so I'll close it an let them comment, I think maybe this is superseded by the locking which might have come later.

I think it could be confusing to alter how the bot handles ending raids after go.
