### ISSUE TITLE
Leaderboard output to display IGN alongside mention

### ISSUE THREAD

**Issue by qwertyperky** [PokeNavBot/Issue-Tracker#574]
**Is your feature request related to a problem? Please describe.**
Issue with discord on mobile/desktop where user mentions in embeds don't display correctly, which the current iteration of the leaderboard commands use.

**Describe the solution you'd like**
If the user has set a IGN, the leaderboard would display this, e.g. "IVpips (@invalid user)" instead of "@invalid user"

**Comment by TheGerontocracy** [comment]
This would be an improvement, but quertyperky (@ invalid-user) or even quertyperky <@!29345545457688> still looks broken too me. My preference is:
`toggle use-ign-for-top-and-drop-members-without-their-ign-set`

**Comment by dandesousa** [comment]
Coming in the next release (default IGN + mention fallback with an option to toggle back the old behavior)
