### ISSUE TITLE
Ability to separate Tiers 

### ISSUE THREAD

**Issue by HaleyATL** [PokeNavBot/Issue-Tracker#577]
As servers grow we see an overwhelming amount of fast clickers who are typically only interested in new T5 bosses. This leads lower tier lobbies to have people clicking in and backing out almost constantly. This issue not only deters lower level hosts, but makes for a bot not used for the full raid rotation. 

**Solution Suggestion:** Have tiers separated through channels such as Active_Raids Tier 1, Tier 3, T5, Mega. The division would keep the clickers in their reserved areas vs assuming what is being posted to one. I'm not sure if this is capable with the screenshot reader, but I believe several servers would take advantage of it. 

I apologize if this has already been suggested – I tried to find it. Thank you!

**Comment by sunkast** [comment]
This already exists to an extent with raid boss restrictions. Take a look at the documentation to see if it would fit your needs.

https://docs.pokenav.app/#/commands/admins_raid_guide?id=raid-boss-restriction

**Comment by HaleyATL** [comment]
And through this restriction we could create multiple active raid channels
based on tiers?
I am not familiar with tech details; I just know my tech team said they
didn't believe this was possible with PokeNav.
(The reason for my suggestion)

Thank you!

**Comment by sunkast** [comment]
No. You can still only have 1 active raids channel per server. Using the raid boss restriction you could create multiple lobbies, restrict each to T5, T3, and T1.

**Comment by HaleyATL** [comment]
Ah so it would still be the same issue. Our server is worldwide so we can't
(on a timezone scale) make an appropriate schedule for the usage to be only
certain tiers. Thus people would still be mass clicking to join raids they
don't particularly want. Thank you for your help!

**Comment by sunkast** [comment]
You would still have those issues with your feature request of multiple active raid channels restricted by tier. The restrict raid boss command does what you ask. The issue of members spamming the invite emoji is a completely separate issue, and one that is being worked on in the future.

**Comment by HaleyATL** [comment]
The mass clicks are regards to everything restricted to one channel.
Whether someone wants a Mega, T5, Tier 3, Tier 1 they're all clicking the
posting hoping it is what they are waiting for. With separate channels
based on tier the people individually waiting for each have a spot where
they wait for one to post. This leads to less in/outs and better product
for a full lobby each time. In one channel these postings simply get pushed
back once they open back up - and unfortunately mobile users (majority in
our member base) aren't going to scroll up and rejoin one. Through this we
have significantly dropped in hosts of lower tiers in which our own hosts
have to make up through waves - and not the bot.

**Comment by dandesousa** [comment]
The concept of active raids and clicking is quickly going to become irrelevant for remote servers in the next month or 2 with the introduction of queues where no one will be clicking anything except a button to wait in line for a raid. 

Active raids are not recommended for busy remote servers anyway as it hurts throughput in high activity servers.

PoGo Ottawa follows the ideal -- setup multiple raid lobbies named for your bosses, set your restrictions, enable slow mode -- and don't enable active raids. And let people just watch the channels they care about.

And wait until the queue feature becomes available.

**Comment by dandesousa** [comment]
I'm closing this because there are no plans to have the bot sort raids for users, and other upcoming features will supersede this
