### ISSUE TITLE
Leaderboard after $reset is not pristine. 

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/Issue-Tracker#579]
**Describe the bug**
Just did $reset-leaderboard on my server and discovered that pokenav fills the first 10 slots with seemingly random members after reset. (Many of which display as <@!user-id>). It's the first time I did $reset-leaderboard so not sure if this is a new bug or if it has always been the behaviour of $top recent.

**To Reproduce**
1. $reset leaderboard 
2. $top

**Expected behavior**
I expect $top after $reset leaderboard to produce a pristine leaderboard with zero members listed. 

**Screenshots**
![IMG_0900](https://user-images.githubusercontent.com/46009436/101330970-93620080-3873-11eb-8a6c-9fd63e2aaa69.jpg)

**Additional context**
I was planning to do a weekly reset every Sunday and let the leaderboard fill during the week but I don't want to display the this.

**Comment by dandesousa** [comment]
It has always been like this but pretty easy to exclude members without a value from the leaderboard.
