### ISSUE TITLE
Toggle !end for moderators only

### ISSUE THREAD

**Issue by ghost** [PokeNavBot/Issue-Tracker#590]
**Is your feature request related to a problem? Please describe.**
When issues arise within the individual channels, hosts may use !end to clear any proof. Users COULD report issues but proof should always be attainable. For those servers that care to attain this proof, they should have a toggle to allow !end to only be used by moderators

**Describe the solution you'd like**
!toggle end-raid-command "ON for all/OFF for moderators only"

**Describe alternatives you've considered**

**Additional context**

**Comment by dandesousa** [comment]
#569 already solves this in a different way. so closing this a duplicate
