### ISSUE TITLE
Allow for use of special boosted raid roles

### ISSUE THREAD

**Issue by ghost** [PokeNavBot/Issue-Tracker#592]
**Is your feature request related to a problem? Please describe.**
Allow support for boosted tags. Currently, we have our own tags in place and the bot picks them up with no issue. We have specific tags in place for those who only want boosted raids and it makes it easier to tag and what not.

**Describe the solution you'd like**
Pokenav to read roles as a pokemon tag
Example:
@Ho-Oh Boosted should hopefully read that its Ho-Oh and boosted
@Heatran Boosted
@Azelf Boosted
so on and so forth

**Describe alternatives you've considered**

**Additional context**

**Comment by dandesousa** [comment]
There is already support for weather boost via the weather raid modifiers. See documentation for raid and create notify-rules

**Comment by ghost** [comment]
> There is already support for weather boost via the weather raid modifiers. See documentation for raid and create notify-rules

Raid modifiers require the user to add additional modifiers making it something more complex for brand new discord users as opposed to just taggins a role with the pokemon and boosted contained within it.

![image](https://user-images.githubusercontent.com/70246298/103469981-0d35be80-4d3a-11eb-9e87-f92f97f7fb80.png)
