### ISSUE TITLE
Add eggs modifier to create raid-boss-restriction

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/Issue-Tracker#593]
**The problem with eggs**
Raids reported before hatch coordinate differently than those reported after hatch. Raids reported as hatched bosses typically launch as soon as there are enough people in the channel. Raids reported as eggs are slower paced and can allow members to go to the spot. On my server I relegate tier 5 eggs to a separate lobby and disallow reporting of eggs of tier 1, 3 and mega. It would be helpful to let pokenav handle the moderation work.

**Proposed solution: Add modifier to disallow eggs to create raid-boss-restriciton**
Currently, egg tiers of the bosses specified are also allowed implicitly. That behavior can be persisted but with a modifier to disallow them, as per the following example: 

`$create raid-boss-restriction #hatched-ho-oh Ho-Oh "disallow_eggs: 1"`

**Alternative solution: Specify maximum minutes allowed before hatch**
Add a modifier specifing the maximum number of minutes until hatch allowed for eggs. This allows raids to be reported shortly before hatch as they can also lauch quickly. Example: 

`$create raid-boss-restriction #ho-oh Ho-Oh "max_egg_duration: 5"`

**Comment by ukbigdave** [comment]
It's a good idea. For me it would be simple enough to have 1 toggle for eggs. Being too specific will confuse users. Maybe per raid channel.

**Comment by dandesousa** [comment]
I think this will end up being a raid lobby setting rather than a part of the boss restrictions -- mostly because it might be confusing to modify a restriction rather than the entire lobby.

**Comment by ukbigdave** [comment]
- [ ] Hahah. Forgot about this ticket. Happy to see it move forward 😎
