### ISSUE TITLE
Link raid parties to other separate categories

### ISSUE THREAD

**Issue by definitivegear** [PokeNavBot/Issue-Tracker#594]
**Is your feature request related to a problem? Please describe.**
Currently, raid party channels are created within the same category as the raid announce channel. This requires separate raid tier categories, which can make the channel list super messy

**Describe the solution you'd like**
The channel list is currently set up as follows:

-tier 5-
#genesect
#raid-party-1
(cont)

-mega-
#megas
#raid-party-1
(cont)

-tier 1/3-
#tier3
#tier1
#raid-party-1
(cont)

Each category has their specific raid party channels created within that category. The solution requested would be to allow Pokenav to link a separate category for each tier/raid announce channel's raid parties, so the main category could be grouped together.

Proposed solution:

-remote raids-
#genesect
#megas
#tier-3
#tier-1

-genesect- (hidden from members)
#raid-party-1
(cont)

-megas- (hidden from members)
#raid-party-1
(cont)

-tier3- (hidden from members)
#raid-party-1
(cont)

**Comment by definitivegear** [comment]
From Shaylinn:

My suggestion would be a command like !set party-category <announceChannel> <targetCategoryID>

So you make the target category, for example "Genesect", grab it's ID, and do 
!set party-category #genesect 123456789123456789

And if you do the command without a categoryID it could clear it back to default behavior.

**Comment by TheGerontocracy** [comment]
I like it, but wouldn't just keeping channels sorted by tier achive the same neatness without adding the overhead of new categories? 

The channel creation command has a position parameter, so that would just be a few lines of cheap code. 
Python Example:
```
def position_of_new_channel(old_tiers, new_tier):
       return next((i for (i, t) in enumerate(old_tiers) if t < new_tier), len(old_tiers))

>> position_of_new_channel([6, 5, 5, 4, 3], 5)
3
```

**Comment by Shaylinn79** [comment]
I agree that having the parties sorted in a general "Raid Parties" category would look cleaner.

The problem is when you go over the 50 channel limit. Perhaps it could include the ability to indicate extra target categories for the spill over once the previous category is full.

**Comment by dandesousa** [comment]
The channel position thing is a pretty light lift and I think everyone would want that so I can definitely add that in. If that satisfies your request, maybe we can make a separate ticket (or change this one) into one that handles the spill over.

**Comment by definitivegear** [comment]
Awesome! To confirm, you were referring to the original proposed idea to add in right?

And then converting this ticket or creating a new one specifically regarding the spillover functionality? If the original request is all set, I don't mind converting this one for the other idea.

**Comment by dandesousa** [comment]
I was actually referring to the keep the channels sorted by tier. 

Before I commit to anything I need to do a little more research actually. Geron's suggestion makes it seems lighter weight than it is, when in fact to position a raid PokeNav would have to query all of the active raids in the server to find their absolute position and tier in the server every time a new raid is made (it doesn't actually do this regularly -- it requests at most one raid and does caching by channel / message ids associated with it). There is a list raid function in PokeNav but its so lightly used its not a good test if this started to be used for every single server especially big ones like Ottawa. So I would need to make sure that PokeNav could handle doing this every time a raid is made on a server or re-factor the code to make it happen.

**Comment by dandesousa** [comment]
TBH I think the original suggestion of party category by tier is probably less work to implement but it would impose additional configuration overhead.

**Comment by definitivegear** [comment]
After thinking on this more - I feel the original idea will become very valuable in cases when there are multiple raid bosses, such as the Kanto tour event with the birds and mewtwo. In the current setting, we're going to have to have a total of 6 (3 birds, mewtwo, megas, tier 1/3) individual categories for each, which will clutter the channel list significantly.

The ability of having

-raids-
#mewtwo
#mewtwo-overfill (See below)
#articuno
#zapdos
#moltres
#megas
#tier3
#tier1

Also opens up the advantage of adding in overfill channels very quickly - thoughts?

**Comment by definitivegear** [comment]
<img width="221" alt="Screen Shot 2021-04-26 at 4 40 13 PM" src="https://user-images.githubusercontent.com/73152000/116171685-3dcda980-a6d7-11eb-8de9-727dafccc450.png">

I would love to not have this and have them all in one category!

**Comment by definitivegear** [comment]
Re-opening this and bumping with the new GO Fest announcement - having 34 categories is going to be an absolute organizational nightmare

We conceptualized what this process could look like:

$set raid-lobby-category #raid-regigigas 747840929096007801

ID being the category ID where the lobbies should be created
If the command is not used, nothing changes and lobbies are created within originating raid announce channel category
If the command is used, default raid lobbies are created within targeted category

**Comment by dandesousa** [comment]
Coming in the next release
