### ISSUE TITLE
grant badge from within raid channel

### ISSUE THREAD

**Issue by poprivett** [PokeNavBot/Issue-Tracker#605]
**Is your feature request related to a problem? Please describe.**
Not really - just an improvement on the process

**Describe the solution you'd like**
Allow the host of the raid permission to grant-badge to the members who have joined their raid.

Allow a toggle to turn on grant-badge ability for the host of a raid.  The host of a raid usually has line of sight of who receives a shundo/hundo/shiny in a raid.  With the toggle on, the host would be able to gb any of their channels raid members who catches a shiny etc.  Once the channel is closed down, the gb permissions would no longer be available until the host posts another raid. 

**Describe alternatives you've considered**
At the moment moderators or members with the gb permission can only grant badges.  This requires a middle man which does work but isn't as streamlined as a host havin this ability.

**Comment by dandesousa** [comment]
You can just grant everyone the badge moderator because anyone can start a raid therefore anyone could start a raid and grant themselves a badge. This way is more direct and doesn't involve a special case toggle.
