### ISSUE TITLE
Include member mention or user.id in trainer profile embed

### ISSUE THREAD

**Issue by Shaylinn79** [PokeNavBot/Issue-Tracker#606]
**Is your feature request related to a problem? Please describe.**
From a bot's perspective, the trainer info embed doesn't have anything in it to identify exactly which user it belongs to.
In a profile settings channel with lots of activity, sometimes more than 1 trainer will do a $trainer or $profile command before PokeNav responds, so it's harder to tell which embed belongs to which user (again, this is from a bot's perspective).

**Describe the solution you'd like**
The trainer info embed could include the user.id, or a user mention from which the bot could retrieve the user.id itself. This could be in the footer for example to not impact the existing layout.

**Describe alternatives you've considered**
The bot can do a $trainer call and read the trainer embed response it gets, but by having the ability to identify the user from the embed, it could just scan/read any embed the users are already doing when viewing their profile.

**Additional comment**
Now that I think about it, if this info was in all profile feedback embeds (meaning the pokenav response from individual commands like $ign, $stc, etc.), that would be even more awesome, as I could update my own records or trigger my own custom behavior if it falls in one of my filters, even if they don't do another $trainer or $profile call when done updating their profile.

**Comment by dandesousa** [comment]
I can add the discord user for sure, but for the other commands we are better off doing an API which would be a separate ticket. Let's start by putting the mention in the embed and see if anything else is needed in the future.

**Comment by dandesousa** [comment]
<img width="532" alt="Screen Shot 2021-01-23 at 6 40 21 AM" src="https://user-images.githubusercontent.com/3880281/105577159-e1f52c80-5d45-11eb-8f76-ecd9f24bafc6.png">

next release.
