### ISSUE TITLE
Ability to enable Auto-Publish for announcement channels

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/Issue-Tracker#608]
Idea/Request: 

`$toggle auto-publish [notification-channel]`

Usage: a toggle setting for notification channels to have the bot (if the notification channel it's publishing to is a channel that supports announcements) auto-publish any pokenav messages.

Alternate idea: make it a notify-rule setting. Allow users to add "auto-publish" as a notification rule. Then the publishing would be on a per notify role basis. 

(PS: Also posted on Discord <https://discordapp.com/channels/427476219890630656/428184847819735040/802758085067145307>)

**Comment by fortepc** [comment]
[updated the request with a more refined version of the idea]

**Comment by dandesousa** [comment]
Could you explain a little more what you are trying to accomplish with this feature? Do you mean a command to setup subscribing to release notes, changes, etc ?
