### ISSUE TITLE
Ignore a member's $verify command if they are already in an active verification process.

### ISSUE THREAD

**Issue by Shaylinn79** [PokeNavBot/Issue-Tracker#613]
**Describe the bug**
While doing a $verify process, doing another $verify command can start another verification process (the member I saw do it posted the 2nd $verify in response to the trainer code question, which accepted the answer due to TC being a free text value).

**Expected behavior**
PokeNav should ignore any new $verify command from a user that is already in a verification process.

**Additional suggestion**
I have also seen members give the answer in command format (ex: answering "$ign TrainerName" to the IGN question). PokeNav could simply process all replies as a text answer to the current question and ignore any commands they include, or perhaps it could even be smarter and if the answer is a valid command, use it (for the IGN example it could just grab the TrainerName and ignore the $ign command part of the reply), and therefore not give an error and instead continue the verification process. (I saw a member not figure it out, and re-start the verify process for each step as he kept doing the corresponding $ command at each reply.)

**Comment by dandesousa** [comment]
Some of the requested behaviors are not easily accomplished without larger changes to the bot so I've implemented the following, I hope will help with at least not allowing commands to interrupt or set the profile attributes to the wrong thing:

- Verify now ignores inputs containing mentions or the guild prefix. These will be ignored completely for the verify question, as though they never typed it to answer the question. The command might still be processed, see below:
- If the command is a valid command it will still be processed.
- If the user tries to `$verify` twice, they'll get an error saying they can only run one verify at once, their position in the current `$verify` will be unchanged.

**Comment by dandesousa** [comment]
This will be in the next release
