### ISSUE TITLE
Unset Raid Category

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/Issue-Tracker#614]
If an admin creates a raid category, all raid parties then get created in the category the admin created. But if the admin wants to change raid parties to be created in the same category as the lobby it was reported it, there is no command to revert or reset the category PokeNav is set to. The only way is to delete the existing category.

Can a command be implemented that allows an admin to revert the set category to default behavior where raid parties are created in the same category as the lobby in which they were reported in?

**Comment by dandesousa** [comment]
scheduled for next release
