### ISSUE TITLE
Validation on trainer code.

### ISSUE THREAD

**Issue by ukbigdave** [PokeNavBot/Issue-Tracker#618]
**Is your feature request related to a problem? Please describe.**
Users are able to copy the full "share my trainer code" text, rather than just copy my code. Also see users enter "trainer code nnnn nnnn nnnn" or "$nnnn nnnn nnnn" This causes issues in raiding. This is not users trying to bypass the validation (they can still enter the wrong code), these are people making mistakes. 

**Describe the solution you'd like**
A validation that the trainer code is a max of 14 (12 numbers plus the 2 spaces). 

**Describe alternatives you've considered**
Training and manual intervention 

**Additional context**
Note the IGN does have some validation built in. I think TC is the only non validated field.

**Comment by TheGerontocracy** [comment]
There could be verification when the trainer-code is submitted via $verify and we still leave it open to users to set something else via $stc before or after $verify.

**Comment by ukbigdave** [comment]
Possibly yes. I only use for remote raiding, so only see it returned back for hosting. I can't see the use  case for having something else in there, but I don't know how it's used elsewhere ;)

**Comment by TheGerontocracy** [comment]
Well, it predates remote raiding, so some people have the habit of putting all sorts of stuff in there like "DM me for trainer code". I'm just suggesting that $verify can include tc verification for new users without breaking the freetext functionality it currently has. Breaking changes are unpopular.

**Comment by FlipsCat** [comment]
personally, I'd rather see a toggle server wide: on/off - stc allows only numbers up to 12/stc allows anything (for servers that allow alts and stuff).  for servers like mine that (even for families) stress one discord one code this would be a major quality of mod life improvement by itself lol.

**Comment by dandesousa** [comment]
A lot of people have existing trainer code schemes, multi-line trainer codes etc. I am open to adding this as a requirement for `verify` that it be a valid trainer code (single), however if the tc is already set it will not ask, regardless of validity.

Then leaving `$stc` open to people putting things in like multiple codes, etc.

This gets you to the point where a new user's code can't be messed up by accident, but users can intentionally change their code later.

I think this satisfies all but let me know if not?

I will probably have to announce the change broadly before I can apply it.

**Comment by dandesousa** [comment]
This will be fixed in the next release
