### ISSUE TITLE
Archive feature for raid-channels

### ISSUE THREAD

**Issue by daadyrbarn** [PokeNavBot/Issue-Tracker#621]
**Is your feature request related to a problem? Please describe.**
Losing content of a raid-channel when it expires.

**Describe the solution you'd like**
A way to "archive" a raid channel. Something like a `$archive` command that deletes the channel-role and moves the channel to an archive category.

Originally suggested by Shadowgreeb:
> After a raid room is terminated with $bye the channel obviously goes away, but could there an optional 'end' type command that could be used to remove the channel tag from participating members, but leave it viewable to moderators/admins?...like an archive for any issues to be reviewed if a moderator is not available at the time?

**Comment by TheGerontocracy** [comment]
How about $archive just tells pokenav not to delete the channel. Such a command could be open to everyone, because it doesn't break the raid-party. Members can still leave the channel if they like, but nobody can $end it and it won't expire. The original channel seems like the natural place for moderators and members to hash out any conflicts.

**Comment by daadyrbarn** [comment]
could be useful as well but not quite the same functionality, so might be better as a separate (or sub-) command.

**Comment by ukbigdave** [comment]
I guess need to consider a category can only have 50 channels. This could fast will on servers doing hundreds, or thousands of raids a day.

**Comment by FlipsCat** [comment]
> How about $archive just tells pokenav not to delete the channel. Such a command could be open to everyone, because it doesn't break the raid-party. Members can still leave the channel if they like, but nobody can $end it and it won't expire. The original channel seems like the natural place for moderators and members to hash out any conflicts.

This is basically what I do just manually. (I usually edit the perms to delete any users and Pokenav's view rights and move the channel to our admin category for review lol). A command just to do this would be nice :)
