### ISSUE TITLE
Allow discord-ids in addition to mentions for $gtc, $trainer-stats, $gb, etc

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/Issue-Tracker#624]
Composing member mentions in channels where the member is not present is tedious. 

It would be helpful to support also discord-ids for these commands via [converters](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#discord-converters)

The ones that come to my mind are:

- gb
- gtc
- here
- profile
- trainer-stats

![IMG_1544](https://user-images.githubusercontent.com/46009436/109646864-ec7ebf00-7b58-11eb-9b08-f23bf1ce74d3.jpg)

**Comment by FlipsCat** [comment]
Agreed. Not sure how Silph Bot did it but you can add/remove staff via ID only and no <@> needed. Less time and easier to teach newer users too

**Comment by dandesousa** [comment]
Coming in the next release.
