### ISSUE TITLE
Add members to raid via mentions in $raid command.

### ISSUE THREAD

**Issue by TheGerontocracy** [PokeNavBot/Issue-Tracker#625]
Sometimes a host has pre-coordinated with other members outside raid channel. A technically skilled can limit the lobby via : 
`>>>$r boss "mm: 4" `
to make sure they don't have to kick anyone from the raid channel. An even more technically skilled host could also make $mi and the leaderboard count work via:
```
>>>$here <@ member1-id>
>>>$here <@ member2-id>
```

Expanding the raid command to `$raid boss "gym" timer [modifiers] [member mentions]` would streamline the process and involve fewer interactions for the bot.

**Comment by FlipsCat** [comment]
This would definitely make my life easier, 100% agree and hope something of this sort becomes implemented!!!

**Comment by TheGerontocracy** [comment]
Changed my mind on this one. I think the cleaner implementation would be to reserve slots for members through a modifier in the command, e.g. $i: 

`$r regigigas 'i: @guest1 @guest2`

That would also work for screenshots then. `$invite @guest` in the raid channel would add guest to the raid channel without setting their status to ready. 

![IMG_2195](https://user-images.githubusercontent.com/46009436/122910472-82339980-d356-11eb-9a29-861a03e48f40.jpeg)
