### ISSUE TITLE
Get server stats for Raids Joined/Created/Reported outside of Leaderboard

### ISSUE THREAD

**Issue by typographynerd** [PokeNavBot/Issue-Tracker#628]
**Is your feature request related to a problem? Please describe.**
Leaderboards only report the top 100 for raids joined, created and reported. Our server has milestone badges for these as incentive for people to be active in the community, for example "Created 50 raids". However, as the server grows, these stats will drop off the leaderboard as more and more people report raids.

**Describe the solution you'd like**
Ideally, it would be great to query the data with specific ranges: for example, generating a lis of users who have reported between 100 and 199 raids.

**Describe alternatives you've considered**
Currently, we are just using leaderboards and have to rely on self-report by members if the milestone is no longer visible on the leaderboard.

**Comment by poprivett** [comment]
This would be really helpful in our server

**Comment by swlondonred** [comment]
Wow cool idea would be great to add to my servers

**Comment by typographynerd** [comment]
Just bumping this request with more info: I did figure a work around which would be blacklisting a number of people so the leaderboard report goes down a bit further. But this is super-tedious and sends a lot of requests to the bot. 

Some way to query the data sounds like a better way to do this!

**Comment by Skyfire2275** [comment]
Would be useful for us too since we assign badges and roles based on the number of raids hosted, and this is the best way to get a list... but once 100 is not enough, our method fails. :(
