### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by Roli0109** [PokeNavBot/Issue-Tracker#632]
A lot of people can't find the player.
 therefore, there may be a new command that can query the database for in-game names.
and the bot responds with the discord ID.

For example

_People_: **$find-ign Roli0109**
_Pokenav_: **Roli2000#7149**

**Comment by MaxEtMoritz** [comment]
This is a duplicate of #598.
Just my thoughts on this, i would find it cool if the command was called `$whois` or if that was at least an alias for it.

**Comment by dandesousa** [comment]
duplicate
