### ISSUE TITLE
Support for XL Pokemon in the $pvpoke command queries.

### ISSUE THREAD

**Issue by AdrianZephyr** [PokeNavBot/Issue-Tracker#634]
**Is your feature request related to a problem? Please describe.**
After a discussion with Pips, it turns out that integration with PvPoke is missing, as regards XL Pokemon. Current integration allows for querying non-XL and shadow mons from the PvPoke database. Since more and more people are powering up mons beyond level 40, getting into PvP, and using the $pvpoke command to learn about XL Pokemon rankings in various GBL leagues as well, it would be great to have XLs in there too, and make use of a complete integration with PvPoke database.

**Describe the solution you'd like**
Following the syntax, a solution to this could be with **-XL** as a suffix. For example: **$pvpoke Azumarill-XL** or **$pvpoke Castform-Rainy-XL** or **$pvpoke Abomasnow-Shadow-XL** (where a suffix is already present as a modifier, the new suffix comes after the older one.)

**Comment by dandesousa** [comment]
Fixed in the next release
