### ISSUE TITLE
Auto Create Rotation Roles

### ISSUE THREAD

**Issue by FlipsCat** [PokeNavBot/Issue-Tracker#638]
Based off following discussion. A way using Celandro's API to auto create the rotation-roles via nav.

![freesnippingtool com_capture_20210522104329](https://user-images.githubusercontent.com/66843159/119230556-b2cfab80-baea-11eb-9370-33766f370821.png)

**Comment by typographynerd** [comment]
Love this idea. I am using Google Sheets and webhook to send commands to PokeNav. This would be even better!
