### ISSUE TITLE
Option for simplified $verify complete embed

### ISSUE THREAD

**Issue by FlipsCat** [PokeNavBot/Issue-Tracker#642]
>**Would like the option for a bare bones $verify complete embed**
![freesnippingtool com_capture_20210627175419](https://user-images.githubusercontent.com/66843159/123560584-25c6e480-d771-11eb-8c50-9ed2544a29d2.png)

>**$verify` command works great! Verify embed upon successful completion causes confusion sometimes:**
>>Embed as is screenshot
![freesnippingtool com_capture_20210627175338](https://user-images.githubusercontent.com/66843159/123560565-0b8d0680-d771-11eb-9cc0-6b60fe51d92c.png)

>**Problems associated with expanded embed**
>>Embed isn't needed. Servers have the option to toggle on/off all these prompts in their verify requirements. Users needing the cheat sheet won't need it until later on. And if they DO need it immediately they probably need more help than is offered in the embed anyways.

>> If more than one user is verifying, this embed WILL cause confusion (chat disappears for other users). Generally leads to other problems such as "too many running verify", users answering someone else's prompt instead of scrolling back up, ect.

>>Embed by your average user is misinterpreted most of the time anyways. Most that do read it and understand will also run *$profile and/or the entire bottom section all at once.

>>Embed also causes confusion as I see a lot reset everything just set because they don't understand that the embed is just for later if needed (and by that point they would have to go search for server help again anyways)

>>Some users run $help immediately, which in my opinion I would omit the crossed out sections anyways. The ones not crossed out I still would edit as I've not once had a user understand what to do even with them... The ones I left uncrossed I _might_ have let them use in their respective channels, but there's not anything here I haven't made a short how to for (similar to most servers).  Also any of those other commands do not need to be run by someone new and verifying 
![freesnippingtool com_capture_20210627180933](https://user-images.githubusercontent.com/66843159/123560911-3bd5a480-d773-11eb-8997-cb925581b028.png)

>**Describe alternatives you've considered**
>>I have added an auto message from Atlas when the verified role is added that directly links another help guide in hopes they click and clear the verify channel right away. I WILL keep this option for the next guide they need if request is accepted. Some don't click the next channel right away though which doesn't solve the above problems.

**Comment by FlipsCat** [comment]
https://github.com/PokeNavBot/issue-tracker/issues/620

would also help fix this issue

**Comment by dandesousa** [comment]
Toggle will be in the next release.
