### ISSUE TITLE
Manually clear raid command/lobby queue

### ISSUE THREAD

**Issue by definitivegear** [PokeNavBot/Issue-Tracker#647]
**Is your feature request related to a problem? Please describe.**
This is a very niche issue, but when too many raid commands are queued up it leads to lobbies opening 15-20 minutes after the command was used in certain cases (new raid boss day, raid hour day). From our understanding, hitting the server cooldown cap clears the queue, but there are situations where the queue floats right under the limit and there's no way to stop commands being added indefinitely

**Describe the solution you'd like**
A command that can be used in the pokenav admin channel to clear pokenav's raid command/lobby queue

eg. $clear queue
- clears all raid commands currently in the pokenav queue

**Comment by Skyfire2275** [comment]
It would be even better to limit the size of the queue to maybe 5 or 10 commands. That way, with a 12 seconds signup period, no lobby is delayed by more than 2 minutes. Basically only allow PokeNav to accept new commands from a channel when its queue for that channel is not full. It does not even need to provide feedback really. When this becomes an issues, users are already not paying attention...

**Comment by dandesousa** [comment]
This has been addressed by suppressing old commands
