### ISSUE TITLE
Prevent Profile Commands In Profile Setup Channel

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/Issue-Tracker#652]
The ability to prevent new members from running profile commands such as $team, $ign, $stc, $country, or $level, from executing in a profile setup channel. Ideally the only command a new member should be able to execute in a profile setup channel is $verify. There are some members who join, see the success message, and then copy the commands from the success message rather than typing $verify.

**Comment by ukbigdave** [comment]
Use $toggle hide-verify-cheatsheet ? How would people update level, name etc if they change it?

**Comment by sunkast** [comment]
I don't want to hide it from the member that is verifying. Just from new members that see the previous member's success message, then completely not read the greeting that they are supposed to run $verify. If they start running the commands that update their profile rather than $verify then they never get the verified role.
