### ISSUE TITLE
Historical/Archive Channel

### ISSUE THREAD

**Issue by itsmeroger** [PokeNavBot/issue-tracker#95]
Would it be possible to have some kind of history channel, where when a raid ends the stats gets reported to it.

num. of participants
maybe even who showed up and who didnt

Some people in my channel like to keep track of #'s for ex-raid purposes #

**Comment by fortepc** [comment]
Specific idea:

`$set raid-log-channel #channel`

At the end of every raid it would post basically the same embed that would show in #active-raids but it would also be nice to include a specific player list. 

I'd personally like to use it linking it to the server's admin only log channel that records as much as possible for future reference.

**Comment by dandesousa** [comment]
Closing this out, thinking about this as part of a history / stats feature. Follow up feature to come
